package com.gravity.common.support.mybatis.auto.model;

import java.util.Date;

public class AdminBasicInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin_basic_info.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin_basic_info.user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin_basic_info.person_name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String personName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin_basic_info.person_department
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String personDepartment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin_basic_info.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin_basic_info.id
	 * @return  the value of admin_basic_info.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin_basic_info.id
	 * @param id  the value for admin_basic_info.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin_basic_info.user_id
	 * @return  the value of admin_basic_info.user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin_basic_info.user_id
	 * @param userId  the value for admin_basic_info.user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin_basic_info.person_name
	 * @return  the value of admin_basic_info.person_name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getPersonName() {
		return personName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin_basic_info.person_name
	 * @param personName  the value for admin_basic_info.person_name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setPersonName(String personName) {
		this.personName = personName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin_basic_info.person_department
	 * @return  the value of admin_basic_info.person_department
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getPersonDepartment() {
		return personDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin_basic_info.person_department
	 * @param personDepartment  the value for admin_basic_info.person_department
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setPersonDepartment(String personDepartment) {
		this.personDepartment = personDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin_basic_info.create_time
	 * @return  the value of admin_basic_info.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin_basic_info.create_time
	 * @param createTime  the value for admin_basic_info.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_basic_info
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		AdminBasicInfo other = (AdminBasicInfo) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
				&& (this.getPersonName() == null ? other.getPersonName() == null : this.getPersonName().equals(
						other.getPersonName()))
				&& (this.getPersonDepartment() == null ? other.getPersonDepartment() == null : this
						.getPersonDepartment().equals(other.getPersonDepartment()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(
						other.getCreateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_basic_info
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
		result = prime * result + ((getPersonName() == null) ? 0 : getPersonName().hashCode());
		result = prime * result + ((getPersonDepartment() == null) ? 0 : getPersonDepartment().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		return result;
	}
}