package com.gravity.common.support.mybatis.auto.model;

import java.util.Date;

public class EmployIdentificationCompany {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employ_identification_company.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employ_identification_company.user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employ_identification_company.company_name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employ_identification_company.corporate_representative
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String corporateRepresentative;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employ_identification_company.company_location_province_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer companyLocationProvinceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employ_identification_company.company_location_city_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer companyLocationCityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employ_identification_company.company_location_town_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer companyLocationTownId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employ_identification_company.company_location
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String companyLocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employ_identification_company.company_location_detail
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String companyLocationDetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employ_identification_company.company_email
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String companyEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employ_identification_company.socialUnifiedCreditCode
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String socialunifiedcreditcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employ_identification_company.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employ_identification_company.update_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employ_identification_company.id
	 * @return  the value of employ_identification_company.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employ_identification_company.id
	 * @param id  the value for employ_identification_company.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employ_identification_company.user_id
	 * @return  the value of employ_identification_company.user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employ_identification_company.user_id
	 * @param userId  the value for employ_identification_company.user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employ_identification_company.company_name
	 * @return  the value of employ_identification_company.company_name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employ_identification_company.company_name
	 * @param companyName  the value for employ_identification_company.company_name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employ_identification_company.corporate_representative
	 * @return  the value of employ_identification_company.corporate_representative
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getCorporateRepresentative() {
		return corporateRepresentative;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employ_identification_company.corporate_representative
	 * @param corporateRepresentative  the value for employ_identification_company.corporate_representative
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCorporateRepresentative(String corporateRepresentative) {
		this.corporateRepresentative = corporateRepresentative;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employ_identification_company.company_location_province_id
	 * @return  the value of employ_identification_company.company_location_province_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getCompanyLocationProvinceId() {
		return companyLocationProvinceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employ_identification_company.company_location_province_id
	 * @param companyLocationProvinceId  the value for employ_identification_company.company_location_province_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyLocationProvinceId(Integer companyLocationProvinceId) {
		this.companyLocationProvinceId = companyLocationProvinceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employ_identification_company.company_location_city_id
	 * @return  the value of employ_identification_company.company_location_city_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getCompanyLocationCityId() {
		return companyLocationCityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employ_identification_company.company_location_city_id
	 * @param companyLocationCityId  the value for employ_identification_company.company_location_city_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyLocationCityId(Integer companyLocationCityId) {
		this.companyLocationCityId = companyLocationCityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employ_identification_company.company_location_town_id
	 * @return  the value of employ_identification_company.company_location_town_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getCompanyLocationTownId() {
		return companyLocationTownId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employ_identification_company.company_location_town_id
	 * @param companyLocationTownId  the value for employ_identification_company.company_location_town_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyLocationTownId(Integer companyLocationTownId) {
		this.companyLocationTownId = companyLocationTownId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employ_identification_company.company_location
	 * @return  the value of employ_identification_company.company_location
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getCompanyLocation() {
		return companyLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employ_identification_company.company_location
	 * @param companyLocation  the value for employ_identification_company.company_location
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyLocation(String companyLocation) {
		this.companyLocation = companyLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employ_identification_company.company_location_detail
	 * @return  the value of employ_identification_company.company_location_detail
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getCompanyLocationDetail() {
		return companyLocationDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employ_identification_company.company_location_detail
	 * @param companyLocationDetail  the value for employ_identification_company.company_location_detail
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyLocationDetail(String companyLocationDetail) {
		this.companyLocationDetail = companyLocationDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employ_identification_company.company_email
	 * @return  the value of employ_identification_company.company_email
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getCompanyEmail() {
		return companyEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employ_identification_company.company_email
	 * @param companyEmail  the value for employ_identification_company.company_email
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyEmail(String companyEmail) {
		this.companyEmail = companyEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employ_identification_company.socialUnifiedCreditCode
	 * @return  the value of employ_identification_company.socialUnifiedCreditCode
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getSocialunifiedcreditcode() {
		return socialunifiedcreditcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employ_identification_company.socialUnifiedCreditCode
	 * @param socialunifiedcreditcode  the value for employ_identification_company.socialUnifiedCreditCode
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setSocialunifiedcreditcode(String socialunifiedcreditcode) {
		this.socialunifiedcreditcode = socialunifiedcreditcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employ_identification_company.create_time
	 * @return  the value of employ_identification_company.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employ_identification_company.create_time
	 * @param createTime  the value for employ_identification_company.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employ_identification_company.update_time
	 * @return  the value of employ_identification_company.update_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employ_identification_company.update_time
	 * @param updateTime  the value for employ_identification_company.update_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		EmployIdentificationCompany other = (EmployIdentificationCompany) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
				&& (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(
						other.getCompanyName()))
				&& (this.getCorporateRepresentative() == null ? other.getCorporateRepresentative() == null : this
						.getCorporateRepresentative().equals(other.getCorporateRepresentative()))
				&& (this.getCompanyLocationProvinceId() == null ? other.getCompanyLocationProvinceId() == null : this
						.getCompanyLocationProvinceId().equals(other.getCompanyLocationProvinceId()))
				&& (this.getCompanyLocationCityId() == null ? other.getCompanyLocationCityId() == null : this
						.getCompanyLocationCityId().equals(other.getCompanyLocationCityId()))
				&& (this.getCompanyLocationTownId() == null ? other.getCompanyLocationTownId() == null : this
						.getCompanyLocationTownId().equals(other.getCompanyLocationTownId()))
				&& (this.getCompanyLocation() == null ? other.getCompanyLocation() == null : this.getCompanyLocation()
						.equals(other.getCompanyLocation()))
				&& (this.getCompanyLocationDetail() == null ? other.getCompanyLocationDetail() == null : this
						.getCompanyLocationDetail().equals(other.getCompanyLocationDetail()))
				&& (this.getCompanyEmail() == null ? other.getCompanyEmail() == null : this.getCompanyEmail().equals(
						other.getCompanyEmail()))
				&& (this.getSocialunifiedcreditcode() == null ? other.getSocialunifiedcreditcode() == null : this
						.getSocialunifiedcreditcode().equals(other.getSocialunifiedcreditcode()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(
						other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(
						other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
		result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
		result = prime * result
				+ ((getCorporateRepresentative() == null) ? 0 : getCorporateRepresentative().hashCode());
		result = prime * result
				+ ((getCompanyLocationProvinceId() == null) ? 0 : getCompanyLocationProvinceId().hashCode());
		result = prime * result + ((getCompanyLocationCityId() == null) ? 0 : getCompanyLocationCityId().hashCode());
		result = prime * result + ((getCompanyLocationTownId() == null) ? 0 : getCompanyLocationTownId().hashCode());
		result = prime * result + ((getCompanyLocation() == null) ? 0 : getCompanyLocation().hashCode());
		result = prime * result + ((getCompanyLocationDetail() == null) ? 0 : getCompanyLocationDetail().hashCode());
		result = prime * result + ((getCompanyEmail() == null) ? 0 : getCompanyEmail().hashCode());
		result = prime * result
				+ ((getSocialunifiedcreditcode() == null) ? 0 : getSocialunifiedcreditcode().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}
}