package com.gravity.common.support.mybatis.auto.model;

import java.util.Date;

public class Evaluate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column evaluate.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column evaluate.id_no
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String idNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column evaluate.service_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer serviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column evaluate.provider_user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer providerUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column evaluate.evaluate_level
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer evaluateLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column evaluate.evaluate_content
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String evaluateContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column evaluate.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column evaluate.id
	 * @return  the value of evaluate.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column evaluate.id
	 * @param id  the value for evaluate.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column evaluate.id_no
	 * @return  the value of evaluate.id_no
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getIdNo() {
		return idNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column evaluate.id_no
	 * @param idNo  the value for evaluate.id_no
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column evaluate.service_id
	 * @return  the value of evaluate.service_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getServiceId() {
		return serviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column evaluate.service_id
	 * @param serviceId  the value for evaluate.service_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column evaluate.provider_user_id
	 * @return  the value of evaluate.provider_user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getProviderUserId() {
		return providerUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column evaluate.provider_user_id
	 * @param providerUserId  the value for evaluate.provider_user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setProviderUserId(Integer providerUserId) {
		this.providerUserId = providerUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column evaluate.evaluate_level
	 * @return  the value of evaluate.evaluate_level
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getEvaluateLevel() {
		return evaluateLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column evaluate.evaluate_level
	 * @param evaluateLevel  the value for evaluate.evaluate_level
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setEvaluateLevel(Integer evaluateLevel) {
		this.evaluateLevel = evaluateLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column evaluate.evaluate_content
	 * @return  the value of evaluate.evaluate_content
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getEvaluateContent() {
		return evaluateContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column evaluate.evaluate_content
	 * @param evaluateContent  the value for evaluate.evaluate_content
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setEvaluateContent(String evaluateContent) {
		this.evaluateContent = evaluateContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column evaluate.create_time
	 * @return  the value of evaluate.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column evaluate.create_time
	 * @param createTime  the value for evaluate.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Evaluate other = (Evaluate) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getIdNo() == null ? other.getIdNo() == null : this.getIdNo().equals(other.getIdNo()))
				&& (this.getServiceId() == null ? other.getServiceId() == null : this.getServiceId().equals(
						other.getServiceId()))
				&& (this.getProviderUserId() == null ? other.getProviderUserId() == null : this.getProviderUserId()
						.equals(other.getProviderUserId()))
				&& (this.getEvaluateLevel() == null ? other.getEvaluateLevel() == null : this.getEvaluateLevel()
						.equals(other.getEvaluateLevel()))
				&& (this.getEvaluateContent() == null ? other.getEvaluateContent() == null : this.getEvaluateContent()
						.equals(other.getEvaluateContent()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(
						other.getCreateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getIdNo() == null) ? 0 : getIdNo().hashCode());
		result = prime * result + ((getServiceId() == null) ? 0 : getServiceId().hashCode());
		result = prime * result + ((getProviderUserId() == null) ? 0 : getProviderUserId().hashCode());
		result = prime * result + ((getEvaluateLevel() == null) ? 0 : getEvaluateLevel().hashCode());
		result = prime * result + ((getEvaluateContent() == null) ? 0 : getEvaluateContent().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		return result;
	}
}