package com.gravity.common.support.mybatis.auto.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EvaluateExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public EvaluateExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNoIsNull() {
			addCriterion("id_no is null");
			return (Criteria) this;
		}

		public Criteria andIdNoIsNotNull() {
			addCriterion("id_no is not null");
			return (Criteria) this;
		}

		public Criteria andIdNoEqualTo(String value) {
			addCriterion("id_no =", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoNotEqualTo(String value) {
			addCriterion("id_no <>", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoGreaterThan(String value) {
			addCriterion("id_no >", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoGreaterThanOrEqualTo(String value) {
			addCriterion("id_no >=", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoLessThan(String value) {
			addCriterion("id_no <", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoLessThanOrEqualTo(String value) {
			addCriterion("id_no <=", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoLike(String value) {
			addCriterion("id_no like", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoNotLike(String value) {
			addCriterion("id_no not like", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoIn(List<String> values) {
			addCriterion("id_no in", values, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoNotIn(List<String> values) {
			addCriterion("id_no not in", values, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoBetween(String value1, String value2) {
			addCriterion("id_no between", value1, value2, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoNotBetween(String value1, String value2) {
			addCriterion("id_no not between", value1, value2, "idNo");
			return (Criteria) this;
		}

		public Criteria andServiceIdIsNull() {
			addCriterion("service_id is null");
			return (Criteria) this;
		}

		public Criteria andServiceIdIsNotNull() {
			addCriterion("service_id is not null");
			return (Criteria) this;
		}

		public Criteria andServiceIdEqualTo(Integer value) {
			addCriterion("service_id =", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdNotEqualTo(Integer value) {
			addCriterion("service_id <>", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdGreaterThan(Integer value) {
			addCriterion("service_id >", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("service_id >=", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdLessThan(Integer value) {
			addCriterion("service_id <", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdLessThanOrEqualTo(Integer value) {
			addCriterion("service_id <=", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdIn(List<Integer> values) {
			addCriterion("service_id in", values, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdNotIn(List<Integer> values) {
			addCriterion("service_id not in", values, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdBetween(Integer value1, Integer value2) {
			addCriterion("service_id between", value1, value2, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("service_id not between", value1, value2, "serviceId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdIsNull() {
			addCriterion("provider_user_id is null");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdIsNotNull() {
			addCriterion("provider_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdEqualTo(Integer value) {
			addCriterion("provider_user_id =", value, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdNotEqualTo(Integer value) {
			addCriterion("provider_user_id <>", value, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdGreaterThan(Integer value) {
			addCriterion("provider_user_id >", value, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("provider_user_id >=", value, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdLessThan(Integer value) {
			addCriterion("provider_user_id <", value, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("provider_user_id <=", value, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdIn(List<Integer> values) {
			addCriterion("provider_user_id in", values, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdNotIn(List<Integer> values) {
			addCriterion("provider_user_id not in", values, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdBetween(Integer value1, Integer value2) {
			addCriterion("provider_user_id between", value1, value2, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("provider_user_id not between", value1, value2, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andEvaluateLevelIsNull() {
			addCriterion("evaluate_level is null");
			return (Criteria) this;
		}

		public Criteria andEvaluateLevelIsNotNull() {
			addCriterion("evaluate_level is not null");
			return (Criteria) this;
		}

		public Criteria andEvaluateLevelEqualTo(Integer value) {
			addCriterion("evaluate_level =", value, "evaluateLevel");
			return (Criteria) this;
		}

		public Criteria andEvaluateLevelNotEqualTo(Integer value) {
			addCriterion("evaluate_level <>", value, "evaluateLevel");
			return (Criteria) this;
		}

		public Criteria andEvaluateLevelGreaterThan(Integer value) {
			addCriterion("evaluate_level >", value, "evaluateLevel");
			return (Criteria) this;
		}

		public Criteria andEvaluateLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("evaluate_level >=", value, "evaluateLevel");
			return (Criteria) this;
		}

		public Criteria andEvaluateLevelLessThan(Integer value) {
			addCriterion("evaluate_level <", value, "evaluateLevel");
			return (Criteria) this;
		}

		public Criteria andEvaluateLevelLessThanOrEqualTo(Integer value) {
			addCriterion("evaluate_level <=", value, "evaluateLevel");
			return (Criteria) this;
		}

		public Criteria andEvaluateLevelIn(List<Integer> values) {
			addCriterion("evaluate_level in", values, "evaluateLevel");
			return (Criteria) this;
		}

		public Criteria andEvaluateLevelNotIn(List<Integer> values) {
			addCriterion("evaluate_level not in", values, "evaluateLevel");
			return (Criteria) this;
		}

		public Criteria andEvaluateLevelBetween(Integer value1, Integer value2) {
			addCriterion("evaluate_level between", value1, value2, "evaluateLevel");
			return (Criteria) this;
		}

		public Criteria andEvaluateLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("evaluate_level not between", value1, value2, "evaluateLevel");
			return (Criteria) this;
		}

		public Criteria andEvaluateContentIsNull() {
			addCriterion("evaluate_content is null");
			return (Criteria) this;
		}

		public Criteria andEvaluateContentIsNotNull() {
			addCriterion("evaluate_content is not null");
			return (Criteria) this;
		}

		public Criteria andEvaluateContentEqualTo(String value) {
			addCriterion("evaluate_content =", value, "evaluateContent");
			return (Criteria) this;
		}

		public Criteria andEvaluateContentNotEqualTo(String value) {
			addCriterion("evaluate_content <>", value, "evaluateContent");
			return (Criteria) this;
		}

		public Criteria andEvaluateContentGreaterThan(String value) {
			addCriterion("evaluate_content >", value, "evaluateContent");
			return (Criteria) this;
		}

		public Criteria andEvaluateContentGreaterThanOrEqualTo(String value) {
			addCriterion("evaluate_content >=", value, "evaluateContent");
			return (Criteria) this;
		}

		public Criteria andEvaluateContentLessThan(String value) {
			addCriterion("evaluate_content <", value, "evaluateContent");
			return (Criteria) this;
		}

		public Criteria andEvaluateContentLessThanOrEqualTo(String value) {
			addCriterion("evaluate_content <=", value, "evaluateContent");
			return (Criteria) this;
		}

		public Criteria andEvaluateContentLike(String value) {
			addCriterion("evaluate_content like", value, "evaluateContent");
			return (Criteria) this;
		}

		public Criteria andEvaluateContentNotLike(String value) {
			addCriterion("evaluate_content not like", value, "evaluateContent");
			return (Criteria) this;
		}

		public Criteria andEvaluateContentIn(List<String> values) {
			addCriterion("evaluate_content in", values, "evaluateContent");
			return (Criteria) this;
		}

		public Criteria andEvaluateContentNotIn(List<String> values) {
			addCriterion("evaluate_content not in", values, "evaluateContent");
			return (Criteria) this;
		}

		public Criteria andEvaluateContentBetween(String value1, String value2) {
			addCriterion("evaluate_content between", value1, value2, "evaluateContent");
			return (Criteria) this;
		}

		public Criteria andEvaluateContentNotBetween(String value1, String value2) {
			addCriterion("evaluate_content not between", value1, value2, "evaluateContent");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table evaluate
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 29 23:52:49 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}