package com.gravity.common.support.mybatis.auto.model;

public class ServiceSales {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_sales.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_sales.service_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer serviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_sales.sales_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer salesNumber;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_sales.id
	 * @return  the value of service_sales.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_sales.id
	 * @param id  the value for service_sales.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_sales.service_id
	 * @return  the value of service_sales.service_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getServiceId() {
		return serviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_sales.service_id
	 * @param serviceId  the value for service_sales.service_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_sales.sales_number
	 * @return  the value of service_sales.sales_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getSalesNumber() {
		return salesNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_sales.sales_number
	 * @param salesNumber  the value for service_sales.sales_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setSalesNumber(Integer salesNumber) {
		this.salesNumber = salesNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ServiceSales other = (ServiceSales) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getServiceId() == null ? other.getServiceId() == null : this.getServiceId().equals(
						other.getServiceId()))
				&& (this.getSalesNumber() == null ? other.getSalesNumber() == null : this.getSalesNumber().equals(
						other.getSalesNumber()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getServiceId() == null) ? 0 : getServiceId().hashCode());
		result = prime * result + ((getSalesNumber() == null) ? 0 : getSalesNumber().hashCode());
		return result;
	}
}