package com.gravity.common.support.mybatis.auto.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ServiceProviderIdentificationPersonExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public ServiceProviderIdentificationPersonExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andIdCardNumberIsNull() {
			addCriterion("id_card_number is null");
			return (Criteria) this;
		}

		public Criteria andIdCardNumberIsNotNull() {
			addCriterion("id_card_number is not null");
			return (Criteria) this;
		}

		public Criteria andIdCardNumberEqualTo(String value) {
			addCriterion("id_card_number =", value, "idCardNumber");
			return (Criteria) this;
		}

		public Criteria andIdCardNumberNotEqualTo(String value) {
			addCriterion("id_card_number <>", value, "idCardNumber");
			return (Criteria) this;
		}

		public Criteria andIdCardNumberGreaterThan(String value) {
			addCriterion("id_card_number >", value, "idCardNumber");
			return (Criteria) this;
		}

		public Criteria andIdCardNumberGreaterThanOrEqualTo(String value) {
			addCriterion("id_card_number >=", value, "idCardNumber");
			return (Criteria) this;
		}

		public Criteria andIdCardNumberLessThan(String value) {
			addCriterion("id_card_number <", value, "idCardNumber");
			return (Criteria) this;
		}

		public Criteria andIdCardNumberLessThanOrEqualTo(String value) {
			addCriterion("id_card_number <=", value, "idCardNumber");
			return (Criteria) this;
		}

		public Criteria andIdCardNumberLike(String value) {
			addCriterion("id_card_number like", value, "idCardNumber");
			return (Criteria) this;
		}

		public Criteria andIdCardNumberNotLike(String value) {
			addCriterion("id_card_number not like", value, "idCardNumber");
			return (Criteria) this;
		}

		public Criteria andIdCardNumberIn(List<String> values) {
			addCriterion("id_card_number in", values, "idCardNumber");
			return (Criteria) this;
		}

		public Criteria andIdCardNumberNotIn(List<String> values) {
			addCriterion("id_card_number not in", values, "idCardNumber");
			return (Criteria) this;
		}

		public Criteria andIdCardNumberBetween(String value1, String value2) {
			addCriterion("id_card_number between", value1, value2, "idCardNumber");
			return (Criteria) this;
		}

		public Criteria andIdCardNumberNotBetween(String value1, String value2) {
			addCriterion("id_card_number not between", value1, value2, "idCardNumber");
			return (Criteria) this;
		}

		public Criteria andLocationProvinceIdIsNull() {
			addCriterion("location_province_id is null");
			return (Criteria) this;
		}

		public Criteria andLocationProvinceIdIsNotNull() {
			addCriterion("location_province_id is not null");
			return (Criteria) this;
		}

		public Criteria andLocationProvinceIdEqualTo(Integer value) {
			addCriterion("location_province_id =", value, "locationProvinceId");
			return (Criteria) this;
		}

		public Criteria andLocationProvinceIdNotEqualTo(Integer value) {
			addCriterion("location_province_id <>", value, "locationProvinceId");
			return (Criteria) this;
		}

		public Criteria andLocationProvinceIdGreaterThan(Integer value) {
			addCriterion("location_province_id >", value, "locationProvinceId");
			return (Criteria) this;
		}

		public Criteria andLocationProvinceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("location_province_id >=", value, "locationProvinceId");
			return (Criteria) this;
		}

		public Criteria andLocationProvinceIdLessThan(Integer value) {
			addCriterion("location_province_id <", value, "locationProvinceId");
			return (Criteria) this;
		}

		public Criteria andLocationProvinceIdLessThanOrEqualTo(Integer value) {
			addCriterion("location_province_id <=", value, "locationProvinceId");
			return (Criteria) this;
		}

		public Criteria andLocationProvinceIdIn(List<Integer> values) {
			addCriterion("location_province_id in", values, "locationProvinceId");
			return (Criteria) this;
		}

		public Criteria andLocationProvinceIdNotIn(List<Integer> values) {
			addCriterion("location_province_id not in", values, "locationProvinceId");
			return (Criteria) this;
		}

		public Criteria andLocationProvinceIdBetween(Integer value1, Integer value2) {
			addCriterion("location_province_id between", value1, value2, "locationProvinceId");
			return (Criteria) this;
		}

		public Criteria andLocationProvinceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("location_province_id not between", value1, value2, "locationProvinceId");
			return (Criteria) this;
		}

		public Criteria andLocationCityIdIsNull() {
			addCriterion("location_city_id is null");
			return (Criteria) this;
		}

		public Criteria andLocationCityIdIsNotNull() {
			addCriterion("location_city_id is not null");
			return (Criteria) this;
		}

		public Criteria andLocationCityIdEqualTo(Integer value) {
			addCriterion("location_city_id =", value, "locationCityId");
			return (Criteria) this;
		}

		public Criteria andLocationCityIdNotEqualTo(Integer value) {
			addCriterion("location_city_id <>", value, "locationCityId");
			return (Criteria) this;
		}

		public Criteria andLocationCityIdGreaterThan(Integer value) {
			addCriterion("location_city_id >", value, "locationCityId");
			return (Criteria) this;
		}

		public Criteria andLocationCityIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("location_city_id >=", value, "locationCityId");
			return (Criteria) this;
		}

		public Criteria andLocationCityIdLessThan(Integer value) {
			addCriterion("location_city_id <", value, "locationCityId");
			return (Criteria) this;
		}

		public Criteria andLocationCityIdLessThanOrEqualTo(Integer value) {
			addCriterion("location_city_id <=", value, "locationCityId");
			return (Criteria) this;
		}

		public Criteria andLocationCityIdIn(List<Integer> values) {
			addCriterion("location_city_id in", values, "locationCityId");
			return (Criteria) this;
		}

		public Criteria andLocationCityIdNotIn(List<Integer> values) {
			addCriterion("location_city_id not in", values, "locationCityId");
			return (Criteria) this;
		}

		public Criteria andLocationCityIdBetween(Integer value1, Integer value2) {
			addCriterion("location_city_id between", value1, value2, "locationCityId");
			return (Criteria) this;
		}

		public Criteria andLocationCityIdNotBetween(Integer value1, Integer value2) {
			addCriterion("location_city_id not between", value1, value2, "locationCityId");
			return (Criteria) this;
		}

		public Criteria andLocationTownIdIsNull() {
			addCriterion("location_town_id is null");
			return (Criteria) this;
		}

		public Criteria andLocationTownIdIsNotNull() {
			addCriterion("location_town_id is not null");
			return (Criteria) this;
		}

		public Criteria andLocationTownIdEqualTo(Integer value) {
			addCriterion("location_town_id =", value, "locationTownId");
			return (Criteria) this;
		}

		public Criteria andLocationTownIdNotEqualTo(Integer value) {
			addCriterion("location_town_id <>", value, "locationTownId");
			return (Criteria) this;
		}

		public Criteria andLocationTownIdGreaterThan(Integer value) {
			addCriterion("location_town_id >", value, "locationTownId");
			return (Criteria) this;
		}

		public Criteria andLocationTownIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("location_town_id >=", value, "locationTownId");
			return (Criteria) this;
		}

		public Criteria andLocationTownIdLessThan(Integer value) {
			addCriterion("location_town_id <", value, "locationTownId");
			return (Criteria) this;
		}

		public Criteria andLocationTownIdLessThanOrEqualTo(Integer value) {
			addCriterion("location_town_id <=", value, "locationTownId");
			return (Criteria) this;
		}

		public Criteria andLocationTownIdIn(List<Integer> values) {
			addCriterion("location_town_id in", values, "locationTownId");
			return (Criteria) this;
		}

		public Criteria andLocationTownIdNotIn(List<Integer> values) {
			addCriterion("location_town_id not in", values, "locationTownId");
			return (Criteria) this;
		}

		public Criteria andLocationTownIdBetween(Integer value1, Integer value2) {
			addCriterion("location_town_id between", value1, value2, "locationTownId");
			return (Criteria) this;
		}

		public Criteria andLocationTownIdNotBetween(Integer value1, Integer value2) {
			addCriterion("location_town_id not between", value1, value2, "locationTownId");
			return (Criteria) this;
		}

		public Criteria andLocationIsNull() {
			addCriterion("location is null");
			return (Criteria) this;
		}

		public Criteria andLocationIsNotNull() {
			addCriterion("location is not null");
			return (Criteria) this;
		}

		public Criteria andLocationEqualTo(String value) {
			addCriterion("location =", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationNotEqualTo(String value) {
			addCriterion("location <>", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationGreaterThan(String value) {
			addCriterion("location >", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationGreaterThanOrEqualTo(String value) {
			addCriterion("location >=", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationLessThan(String value) {
			addCriterion("location <", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationLessThanOrEqualTo(String value) {
			addCriterion("location <=", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationLike(String value) {
			addCriterion("location like", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationNotLike(String value) {
			addCriterion("location not like", value, "location");
			return (Criteria) this;
		}

		public Criteria andLocationIn(List<String> values) {
			addCriterion("location in", values, "location");
			return (Criteria) this;
		}

		public Criteria andLocationNotIn(List<String> values) {
			addCriterion("location not in", values, "location");
			return (Criteria) this;
		}

		public Criteria andLocationBetween(String value1, String value2) {
			addCriterion("location between", value1, value2, "location");
			return (Criteria) this;
		}

		public Criteria andLocationNotBetween(String value1, String value2) {
			addCriterion("location not between", value1, value2, "location");
			return (Criteria) this;
		}

		public Criteria andBankCardIdIsNull() {
			addCriterion("bank_card_id is null");
			return (Criteria) this;
		}

		public Criteria andBankCardIdIsNotNull() {
			addCriterion("bank_card_id is not null");
			return (Criteria) this;
		}

		public Criteria andBankCardIdEqualTo(String value) {
			addCriterion("bank_card_id =", value, "bankCardId");
			return (Criteria) this;
		}

		public Criteria andBankCardIdNotEqualTo(String value) {
			addCriterion("bank_card_id <>", value, "bankCardId");
			return (Criteria) this;
		}

		public Criteria andBankCardIdGreaterThan(String value) {
			addCriterion("bank_card_id >", value, "bankCardId");
			return (Criteria) this;
		}

		public Criteria andBankCardIdGreaterThanOrEqualTo(String value) {
			addCriterion("bank_card_id >=", value, "bankCardId");
			return (Criteria) this;
		}

		public Criteria andBankCardIdLessThan(String value) {
			addCriterion("bank_card_id <", value, "bankCardId");
			return (Criteria) this;
		}

		public Criteria andBankCardIdLessThanOrEqualTo(String value) {
			addCriterion("bank_card_id <=", value, "bankCardId");
			return (Criteria) this;
		}

		public Criteria andBankCardIdLike(String value) {
			addCriterion("bank_card_id like", value, "bankCardId");
			return (Criteria) this;
		}

		public Criteria andBankCardIdNotLike(String value) {
			addCriterion("bank_card_id not like", value, "bankCardId");
			return (Criteria) this;
		}

		public Criteria andBankCardIdIn(List<String> values) {
			addCriterion("bank_card_id in", values, "bankCardId");
			return (Criteria) this;
		}

		public Criteria andBankCardIdNotIn(List<String> values) {
			addCriterion("bank_card_id not in", values, "bankCardId");
			return (Criteria) this;
		}

		public Criteria andBankCardIdBetween(String value1, String value2) {
			addCriterion("bank_card_id between", value1, value2, "bankCardId");
			return (Criteria) this;
		}

		public Criteria andBankCardIdNotBetween(String value1, String value2) {
			addCriterion("bank_card_id not between", value1, value2, "bankCardId");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIsNull() {
			addCriterion("phone_number is null");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIsNotNull() {
			addCriterion("phone_number is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberEqualTo(String value) {
			addCriterion("phone_number =", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotEqualTo(String value) {
			addCriterion("phone_number <>", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberGreaterThan(String value) {
			addCriterion("phone_number >", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
			addCriterion("phone_number >=", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLessThan(String value) {
			addCriterion("phone_number <", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
			addCriterion("phone_number <=", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLike(String value) {
			addCriterion("phone_number like", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotLike(String value) {
			addCriterion("phone_number not like", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIn(List<String> values) {
			addCriterion("phone_number in", values, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotIn(List<String> values) {
			addCriterion("phone_number not in", values, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberBetween(String value1, String value2) {
			addCriterion("phone_number between", value1, value2, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotBetween(String value1, String value2) {
			addCriterion("phone_number not between", value1, value2, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andImgSrcListIsNull() {
			addCriterion("img_src_list is null");
			return (Criteria) this;
		}

		public Criteria andImgSrcListIsNotNull() {
			addCriterion("img_src_list is not null");
			return (Criteria) this;
		}

		public Criteria andImgSrcListEqualTo(String value) {
			addCriterion("img_src_list =", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListNotEqualTo(String value) {
			addCriterion("img_src_list <>", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListGreaterThan(String value) {
			addCriterion("img_src_list >", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListGreaterThanOrEqualTo(String value) {
			addCriterion("img_src_list >=", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListLessThan(String value) {
			addCriterion("img_src_list <", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListLessThanOrEqualTo(String value) {
			addCriterion("img_src_list <=", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListLike(String value) {
			addCriterion("img_src_list like", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListNotLike(String value) {
			addCriterion("img_src_list not like", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListIn(List<String> values) {
			addCriterion("img_src_list in", values, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListNotIn(List<String> values) {
			addCriterion("img_src_list not in", values, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListBetween(String value1, String value2) {
			addCriterion("img_src_list between", value1, value2, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListNotBetween(String value1, String value2) {
			addCriterion("img_src_list not between", value1, value2, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcIsNull() {
			addCriterion("store_display_img_src is null");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcIsNotNull() {
			addCriterion("store_display_img_src is not null");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcEqualTo(String value) {
			addCriterion("store_display_img_src =", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcNotEqualTo(String value) {
			addCriterion("store_display_img_src <>", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcGreaterThan(String value) {
			addCriterion("store_display_img_src >", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcGreaterThanOrEqualTo(String value) {
			addCriterion("store_display_img_src >=", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcLessThan(String value) {
			addCriterion("store_display_img_src <", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcLessThanOrEqualTo(String value) {
			addCriterion("store_display_img_src <=", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcLike(String value) {
			addCriterion("store_display_img_src like", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcNotLike(String value) {
			addCriterion("store_display_img_src not like", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcIn(List<String> values) {
			addCriterion("store_display_img_src in", values, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcNotIn(List<String> values) {
			addCriterion("store_display_img_src not in", values, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcBetween(String value1, String value2) {
			addCriterion("store_display_img_src between", value1, value2, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcNotBetween(String value1, String value2) {
			addCriterion("store_display_img_src not between", value1, value2, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andIsApproveIsNull() {
			addCriterion("is_approve is null");
			return (Criteria) this;
		}

		public Criteria andIsApproveIsNotNull() {
			addCriterion("is_approve is not null");
			return (Criteria) this;
		}

		public Criteria andIsApproveEqualTo(Integer value) {
			addCriterion("is_approve =", value, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveNotEqualTo(Integer value) {
			addCriterion("is_approve <>", value, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveGreaterThan(Integer value) {
			addCriterion("is_approve >", value, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_approve >=", value, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveLessThan(Integer value) {
			addCriterion("is_approve <", value, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveLessThanOrEqualTo(Integer value) {
			addCriterion("is_approve <=", value, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveIn(List<Integer> values) {
			addCriterion("is_approve in", values, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveNotIn(List<Integer> values) {
			addCriterion("is_approve not in", values, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveBetween(Integer value1, Integer value2) {
			addCriterion("is_approve between", value1, value2, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveNotBetween(Integer value1, Integer value2) {
			addCriterion("is_approve not between", value1, value2, "isApprove");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table service_provider_identification_person
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 15 20:39:50 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}