package com.gravity.common.support.mybatis.auto.model;

import java.util.Date;

public class ServiceProviderIdentificationPerson {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.id_card_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String idCardNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.location_province_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer locationProvinceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.location_city_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer locationCityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.location_town_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer locationTownId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.location
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String location;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.bank_card_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String bankCardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.phone_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String phoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.email
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.img_src_list
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String imgSrcList;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.store_display_img_src
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String storeDisplayImgSrc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.is_approve
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer isApprove;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_person.update_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.id
	 * @return  the value of service_provider_identification_person.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.id
	 * @param id  the value for service_provider_identification_person.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.user_id
	 * @return  the value of service_provider_identification_person.user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.user_id
	 * @param userId  the value for service_provider_identification_person.user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.name
	 * @return  the value of service_provider_identification_person.name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.name
	 * @param name  the value for service_provider_identification_person.name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.id_card_number
	 * @return  the value of service_provider_identification_person.id_card_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getIdCardNumber() {
		return idCardNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.id_card_number
	 * @param idCardNumber  the value for service_provider_identification_person.id_card_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setIdCardNumber(String idCardNumber) {
		this.idCardNumber = idCardNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.location_province_id
	 * @return  the value of service_provider_identification_person.location_province_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getLocationProvinceId() {
		return locationProvinceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.location_province_id
	 * @param locationProvinceId  the value for service_provider_identification_person.location_province_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setLocationProvinceId(Integer locationProvinceId) {
		this.locationProvinceId = locationProvinceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.location_city_id
	 * @return  the value of service_provider_identification_person.location_city_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getLocationCityId() {
		return locationCityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.location_city_id
	 * @param locationCityId  the value for service_provider_identification_person.location_city_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setLocationCityId(Integer locationCityId) {
		this.locationCityId = locationCityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.location_town_id
	 * @return  the value of service_provider_identification_person.location_town_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getLocationTownId() {
		return locationTownId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.location_town_id
	 * @param locationTownId  the value for service_provider_identification_person.location_town_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setLocationTownId(Integer locationTownId) {
		this.locationTownId = locationTownId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.location
	 * @return  the value of service_provider_identification_person.location
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getLocation() {
		return location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.location
	 * @param location  the value for service_provider_identification_person.location
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setLocation(String location) {
		this.location = location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.bank_card_id
	 * @return  the value of service_provider_identification_person.bank_card_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getBankCardId() {
		return bankCardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.bank_card_id
	 * @param bankCardId  the value for service_provider_identification_person.bank_card_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setBankCardId(String bankCardId) {
		this.bankCardId = bankCardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.phone_number
	 * @return  the value of service_provider_identification_person.phone_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.phone_number
	 * @param phoneNumber  the value for service_provider_identification_person.phone_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.email
	 * @return  the value of service_provider_identification_person.email
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.email
	 * @param email  the value for service_provider_identification_person.email
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.img_src_list
	 * @return  the value of service_provider_identification_person.img_src_list
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getImgSrcList() {
		return imgSrcList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.img_src_list
	 * @param imgSrcList  the value for service_provider_identification_person.img_src_list
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setImgSrcList(String imgSrcList) {
		this.imgSrcList = imgSrcList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.store_display_img_src
	 * @return  the value of service_provider_identification_person.store_display_img_src
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getStoreDisplayImgSrc() {
		return storeDisplayImgSrc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.store_display_img_src
	 * @param storeDisplayImgSrc  the value for service_provider_identification_person.store_display_img_src
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setStoreDisplayImgSrc(String storeDisplayImgSrc) {
		this.storeDisplayImgSrc = storeDisplayImgSrc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.is_approve
	 * @return  the value of service_provider_identification_person.is_approve
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getIsApprove() {
		return isApprove;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.is_approve
	 * @param isApprove  the value for service_provider_identification_person.is_approve
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setIsApprove(Integer isApprove) {
		this.isApprove = isApprove;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.create_time
	 * @return  the value of service_provider_identification_person.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.create_time
	 * @param createTime  the value for service_provider_identification_person.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_person.update_time
	 * @return  the value of service_provider_identification_person.update_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_person.update_time
	 * @param updateTime  the value for service_provider_identification_person.update_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ServiceProviderIdentificationPerson other = (ServiceProviderIdentificationPerson) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getIdCardNumber() == null ? other.getIdCardNumber() == null : this.getIdCardNumber().equals(
						other.getIdCardNumber()))
				&& (this.getLocationProvinceId() == null ? other.getLocationProvinceId() == null : this
						.getLocationProvinceId().equals(other.getLocationProvinceId()))
				&& (this.getLocationCityId() == null ? other.getLocationCityId() == null : this.getLocationCityId()
						.equals(other.getLocationCityId()))
				&& (this.getLocationTownId() == null ? other.getLocationTownId() == null : this.getLocationTownId()
						.equals(other.getLocationTownId()))
				&& (this.getLocation() == null ? other.getLocation() == null : this.getLocation().equals(
						other.getLocation()))
				&& (this.getBankCardId() == null ? other.getBankCardId() == null : this.getBankCardId().equals(
						other.getBankCardId()))
				&& (this.getPhoneNumber() == null ? other.getPhoneNumber() == null : this.getPhoneNumber().equals(
						other.getPhoneNumber()))
				&& (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
				&& (this.getImgSrcList() == null ? other.getImgSrcList() == null : this.getImgSrcList().equals(
						other.getImgSrcList()))
				&& (this.getStoreDisplayImgSrc() == null ? other.getStoreDisplayImgSrc() == null : this
						.getStoreDisplayImgSrc().equals(other.getStoreDisplayImgSrc()))
				&& (this.getIsApprove() == null ? other.getIsApprove() == null : this.getIsApprove().equals(
						other.getIsApprove()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(
						other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(
						other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getIdCardNumber() == null) ? 0 : getIdCardNumber().hashCode());
		result = prime * result + ((getLocationProvinceId() == null) ? 0 : getLocationProvinceId().hashCode());
		result = prime * result + ((getLocationCityId() == null) ? 0 : getLocationCityId().hashCode());
		result = prime * result + ((getLocationTownId() == null) ? 0 : getLocationTownId().hashCode());
		result = prime * result + ((getLocation() == null) ? 0 : getLocation().hashCode());
		result = prime * result + ((getBankCardId() == null) ? 0 : getBankCardId().hashCode());
		result = prime * result + ((getPhoneNumber() == null) ? 0 : getPhoneNumber().hashCode());
		result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
		result = prime * result + ((getImgSrcList() == null) ? 0 : getImgSrcList().hashCode());
		result = prime * result + ((getStoreDisplayImgSrc() == null) ? 0 : getStoreDisplayImgSrc().hashCode());
		result = prime * result + ((getIsApprove() == null) ? 0 : getIsApprove().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}
}