package com.gravity.common.support.mybatis.auto.model;

import java.util.Date;

public class ServiceProviderIdentificationCompany {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.company_name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.corporate_representative
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String corporateRepresentative;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.company_location_province_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer companyLocationProvinceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.company_location_city_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer companyLocationCityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.company_location_town_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer companyLocationTownId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.company_location
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String companyLocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.company_location_detail
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String companyLocationDetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.contacts_name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String contactsName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.company_email
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String companyEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.company_bank_account
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String companyBankAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.phone_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String phoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.socialUnifiedCreditCode
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String socialunifiedcreditcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.img_src_list
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String imgSrcList;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.store_display_img_src
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String storeDisplayImgSrc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.is_approve
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer isApprove;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.update_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_provider_identification_company.company_profile
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String companyProfile;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.id
	 * @return  the value of service_provider_identification_company.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.id
	 * @param id  the value for service_provider_identification_company.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.user_id
	 * @return  the value of service_provider_identification_company.user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.user_id
	 * @param userId  the value for service_provider_identification_company.user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.company_name
	 * @return  the value of service_provider_identification_company.company_name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.company_name
	 * @param companyName  the value for service_provider_identification_company.company_name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.corporate_representative
	 * @return  the value of service_provider_identification_company.corporate_representative
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getCorporateRepresentative() {
		return corporateRepresentative;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.corporate_representative
	 * @param corporateRepresentative  the value for service_provider_identification_company.corporate_representative
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCorporateRepresentative(String corporateRepresentative) {
		this.corporateRepresentative = corporateRepresentative;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.company_location_province_id
	 * @return  the value of service_provider_identification_company.company_location_province_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getCompanyLocationProvinceId() {
		return companyLocationProvinceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.company_location_province_id
	 * @param companyLocationProvinceId  the value for service_provider_identification_company.company_location_province_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyLocationProvinceId(Integer companyLocationProvinceId) {
		this.companyLocationProvinceId = companyLocationProvinceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.company_location_city_id
	 * @return  the value of service_provider_identification_company.company_location_city_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getCompanyLocationCityId() {
		return companyLocationCityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.company_location_city_id
	 * @param companyLocationCityId  the value for service_provider_identification_company.company_location_city_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyLocationCityId(Integer companyLocationCityId) {
		this.companyLocationCityId = companyLocationCityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.company_location_town_id
	 * @return  the value of service_provider_identification_company.company_location_town_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getCompanyLocationTownId() {
		return companyLocationTownId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.company_location_town_id
	 * @param companyLocationTownId  the value for service_provider_identification_company.company_location_town_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyLocationTownId(Integer companyLocationTownId) {
		this.companyLocationTownId = companyLocationTownId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.company_location
	 * @return  the value of service_provider_identification_company.company_location
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getCompanyLocation() {
		return companyLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.company_location
	 * @param companyLocation  the value for service_provider_identification_company.company_location
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyLocation(String companyLocation) {
		this.companyLocation = companyLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.company_location_detail
	 * @return  the value of service_provider_identification_company.company_location_detail
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getCompanyLocationDetail() {
		return companyLocationDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.company_location_detail
	 * @param companyLocationDetail  the value for service_provider_identification_company.company_location_detail
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyLocationDetail(String companyLocationDetail) {
		this.companyLocationDetail = companyLocationDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.contacts_name
	 * @return  the value of service_provider_identification_company.contacts_name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getContactsName() {
		return contactsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.contacts_name
	 * @param contactsName  the value for service_provider_identification_company.contacts_name
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setContactsName(String contactsName) {
		this.contactsName = contactsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.company_email
	 * @return  the value of service_provider_identification_company.company_email
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getCompanyEmail() {
		return companyEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.company_email
	 * @param companyEmail  the value for service_provider_identification_company.company_email
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyEmail(String companyEmail) {
		this.companyEmail = companyEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.company_bank_account
	 * @return  the value of service_provider_identification_company.company_bank_account
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getCompanyBankAccount() {
		return companyBankAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.company_bank_account
	 * @param companyBankAccount  the value for service_provider_identification_company.company_bank_account
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyBankAccount(String companyBankAccount) {
		this.companyBankAccount = companyBankAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.phone_number
	 * @return  the value of service_provider_identification_company.phone_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.phone_number
	 * @param phoneNumber  the value for service_provider_identification_company.phone_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.socialUnifiedCreditCode
	 * @return  the value of service_provider_identification_company.socialUnifiedCreditCode
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getSocialunifiedcreditcode() {
		return socialunifiedcreditcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.socialUnifiedCreditCode
	 * @param socialunifiedcreditcode  the value for service_provider_identification_company.socialUnifiedCreditCode
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setSocialunifiedcreditcode(String socialunifiedcreditcode) {
		this.socialunifiedcreditcode = socialunifiedcreditcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.img_src_list
	 * @return  the value of service_provider_identification_company.img_src_list
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getImgSrcList() {
		return imgSrcList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.img_src_list
	 * @param imgSrcList  the value for service_provider_identification_company.img_src_list
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setImgSrcList(String imgSrcList) {
		this.imgSrcList = imgSrcList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.store_display_img_src
	 * @return  the value of service_provider_identification_company.store_display_img_src
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getStoreDisplayImgSrc() {
		return storeDisplayImgSrc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.store_display_img_src
	 * @param storeDisplayImgSrc  the value for service_provider_identification_company.store_display_img_src
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setStoreDisplayImgSrc(String storeDisplayImgSrc) {
		this.storeDisplayImgSrc = storeDisplayImgSrc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.is_approve
	 * @return  the value of service_provider_identification_company.is_approve
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getIsApprove() {
		return isApprove;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.is_approve
	 * @param isApprove  the value for service_provider_identification_company.is_approve
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setIsApprove(Integer isApprove) {
		this.isApprove = isApprove;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.create_time
	 * @return  the value of service_provider_identification_company.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.create_time
	 * @param createTime  the value for service_provider_identification_company.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.update_time
	 * @return  the value of service_provider_identification_company.update_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.update_time
	 * @param updateTime  the value for service_provider_identification_company.update_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_provider_identification_company.company_profile
	 * @return  the value of service_provider_identification_company.company_profile
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getCompanyProfile() {
		return companyProfile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_provider_identification_company.company_profile
	 * @param companyProfile  the value for service_provider_identification_company.company_profile
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCompanyProfile(String companyProfile) {
		this.companyProfile = companyProfile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ServiceProviderIdentificationCompany other = (ServiceProviderIdentificationCompany) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
				&& (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(
						other.getCompanyName()))
				&& (this.getCorporateRepresentative() == null ? other.getCorporateRepresentative() == null : this
						.getCorporateRepresentative().equals(other.getCorporateRepresentative()))
				&& (this.getCompanyLocationProvinceId() == null ? other.getCompanyLocationProvinceId() == null : this
						.getCompanyLocationProvinceId().equals(other.getCompanyLocationProvinceId()))
				&& (this.getCompanyLocationCityId() == null ? other.getCompanyLocationCityId() == null : this
						.getCompanyLocationCityId().equals(other.getCompanyLocationCityId()))
				&& (this.getCompanyLocationTownId() == null ? other.getCompanyLocationTownId() == null : this
						.getCompanyLocationTownId().equals(other.getCompanyLocationTownId()))
				&& (this.getCompanyLocation() == null ? other.getCompanyLocation() == null : this.getCompanyLocation()
						.equals(other.getCompanyLocation()))
				&& (this.getCompanyLocationDetail() == null ? other.getCompanyLocationDetail() == null : this
						.getCompanyLocationDetail().equals(other.getCompanyLocationDetail()))
				&& (this.getContactsName() == null ? other.getContactsName() == null : this.getContactsName().equals(
						other.getContactsName()))
				&& (this.getCompanyEmail() == null ? other.getCompanyEmail() == null : this.getCompanyEmail().equals(
						other.getCompanyEmail()))
				&& (this.getCompanyBankAccount() == null ? other.getCompanyBankAccount() == null : this
						.getCompanyBankAccount().equals(other.getCompanyBankAccount()))
				&& (this.getPhoneNumber() == null ? other.getPhoneNumber() == null : this.getPhoneNumber().equals(
						other.getPhoneNumber()))
				&& (this.getSocialunifiedcreditcode() == null ? other.getSocialunifiedcreditcode() == null : this
						.getSocialunifiedcreditcode().equals(other.getSocialunifiedcreditcode()))
				&& (this.getImgSrcList() == null ? other.getImgSrcList() == null : this.getImgSrcList().equals(
						other.getImgSrcList()))
				&& (this.getStoreDisplayImgSrc() == null ? other.getStoreDisplayImgSrc() == null : this
						.getStoreDisplayImgSrc().equals(other.getStoreDisplayImgSrc()))
				&& (this.getIsApprove() == null ? other.getIsApprove() == null : this.getIsApprove().equals(
						other.getIsApprove()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(
						other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(
						other.getUpdateTime()))
				&& (this.getCompanyProfile() == null ? other.getCompanyProfile() == null : this.getCompanyProfile()
						.equals(other.getCompanyProfile()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
		result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
		result = prime * result
				+ ((getCorporateRepresentative() == null) ? 0 : getCorporateRepresentative().hashCode());
		result = prime * result
				+ ((getCompanyLocationProvinceId() == null) ? 0 : getCompanyLocationProvinceId().hashCode());
		result = prime * result + ((getCompanyLocationCityId() == null) ? 0 : getCompanyLocationCityId().hashCode());
		result = prime * result + ((getCompanyLocationTownId() == null) ? 0 : getCompanyLocationTownId().hashCode());
		result = prime * result + ((getCompanyLocation() == null) ? 0 : getCompanyLocation().hashCode());
		result = prime * result + ((getCompanyLocationDetail() == null) ? 0 : getCompanyLocationDetail().hashCode());
		result = prime * result + ((getContactsName() == null) ? 0 : getContactsName().hashCode());
		result = prime * result + ((getCompanyEmail() == null) ? 0 : getCompanyEmail().hashCode());
		result = prime * result + ((getCompanyBankAccount() == null) ? 0 : getCompanyBankAccount().hashCode());
		result = prime * result + ((getPhoneNumber() == null) ? 0 : getPhoneNumber().hashCode());
		result = prime * result
				+ ((getSocialunifiedcreditcode() == null) ? 0 : getSocialunifiedcreditcode().hashCode());
		result = prime * result + ((getImgSrcList() == null) ? 0 : getImgSrcList().hashCode());
		result = prime * result + ((getStoreDisplayImgSrc() == null) ? 0 : getStoreDisplayImgSrc().hashCode());
		result = prime * result + ((getIsApprove() == null) ? 0 : getIsApprove().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getCompanyProfile() == null) ? 0 : getCompanyProfile().hashCode());
		return result;
	}
}