package com.gravity.common.support.mybatis.auto.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ServiceProviderIdentificationCompanyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public ServiceProviderIdentificationCompanyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIsNull() {
			addCriterion("company_name is null");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIsNotNull() {
			addCriterion("company_name is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyNameEqualTo(String value) {
			addCriterion("company_name =", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotEqualTo(String value) {
			addCriterion("company_name <>", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameGreaterThan(String value) {
			addCriterion("company_name >", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
			addCriterion("company_name >=", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLessThan(String value) {
			addCriterion("company_name <", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLessThanOrEqualTo(String value) {
			addCriterion("company_name <=", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLike(String value) {
			addCriterion("company_name like", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotLike(String value) {
			addCriterion("company_name not like", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIn(List<String> values) {
			addCriterion("company_name in", values, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotIn(List<String> values) {
			addCriterion("company_name not in", values, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameBetween(String value1, String value2) {
			addCriterion("company_name between", value1, value2, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotBetween(String value1, String value2) {
			addCriterion("company_name not between", value1, value2, "companyName");
			return (Criteria) this;
		}

		public Criteria andCorporateRepresentativeIsNull() {
			addCriterion("corporate_representative is null");
			return (Criteria) this;
		}

		public Criteria andCorporateRepresentativeIsNotNull() {
			addCriterion("corporate_representative is not null");
			return (Criteria) this;
		}

		public Criteria andCorporateRepresentativeEqualTo(String value) {
			addCriterion("corporate_representative =", value, "corporateRepresentative");
			return (Criteria) this;
		}

		public Criteria andCorporateRepresentativeNotEqualTo(String value) {
			addCriterion("corporate_representative <>", value, "corporateRepresentative");
			return (Criteria) this;
		}

		public Criteria andCorporateRepresentativeGreaterThan(String value) {
			addCriterion("corporate_representative >", value, "corporateRepresentative");
			return (Criteria) this;
		}

		public Criteria andCorporateRepresentativeGreaterThanOrEqualTo(String value) {
			addCriterion("corporate_representative >=", value, "corporateRepresentative");
			return (Criteria) this;
		}

		public Criteria andCorporateRepresentativeLessThan(String value) {
			addCriterion("corporate_representative <", value, "corporateRepresentative");
			return (Criteria) this;
		}

		public Criteria andCorporateRepresentativeLessThanOrEqualTo(String value) {
			addCriterion("corporate_representative <=", value, "corporateRepresentative");
			return (Criteria) this;
		}

		public Criteria andCorporateRepresentativeLike(String value) {
			addCriterion("corporate_representative like", value, "corporateRepresentative");
			return (Criteria) this;
		}

		public Criteria andCorporateRepresentativeNotLike(String value) {
			addCriterion("corporate_representative not like", value, "corporateRepresentative");
			return (Criteria) this;
		}

		public Criteria andCorporateRepresentativeIn(List<String> values) {
			addCriterion("corporate_representative in", values, "corporateRepresentative");
			return (Criteria) this;
		}

		public Criteria andCorporateRepresentativeNotIn(List<String> values) {
			addCriterion("corporate_representative not in", values, "corporateRepresentative");
			return (Criteria) this;
		}

		public Criteria andCorporateRepresentativeBetween(String value1, String value2) {
			addCriterion("corporate_representative between", value1, value2, "corporateRepresentative");
			return (Criteria) this;
		}

		public Criteria andCorporateRepresentativeNotBetween(String value1, String value2) {
			addCriterion("corporate_representative not between", value1, value2, "corporateRepresentative");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationProvinceIdIsNull() {
			addCriterion("company_location_province_id is null");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationProvinceIdIsNotNull() {
			addCriterion("company_location_province_id is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationProvinceIdEqualTo(Integer value) {
			addCriterion("company_location_province_id =", value, "companyLocationProvinceId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationProvinceIdNotEqualTo(Integer value) {
			addCriterion("company_location_province_id <>", value, "companyLocationProvinceId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationProvinceIdGreaterThan(Integer value) {
			addCriterion("company_location_province_id >", value, "companyLocationProvinceId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationProvinceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("company_location_province_id >=", value, "companyLocationProvinceId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationProvinceIdLessThan(Integer value) {
			addCriterion("company_location_province_id <", value, "companyLocationProvinceId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationProvinceIdLessThanOrEqualTo(Integer value) {
			addCriterion("company_location_province_id <=", value, "companyLocationProvinceId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationProvinceIdIn(List<Integer> values) {
			addCriterion("company_location_province_id in", values, "companyLocationProvinceId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationProvinceIdNotIn(List<Integer> values) {
			addCriterion("company_location_province_id not in", values, "companyLocationProvinceId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationProvinceIdBetween(Integer value1, Integer value2) {
			addCriterion("company_location_province_id between", value1, value2, "companyLocationProvinceId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationProvinceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("company_location_province_id not between", value1, value2, "companyLocationProvinceId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationCityIdIsNull() {
			addCriterion("company_location_city_id is null");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationCityIdIsNotNull() {
			addCriterion("company_location_city_id is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationCityIdEqualTo(Integer value) {
			addCriterion("company_location_city_id =", value, "companyLocationCityId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationCityIdNotEqualTo(Integer value) {
			addCriterion("company_location_city_id <>", value, "companyLocationCityId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationCityIdGreaterThan(Integer value) {
			addCriterion("company_location_city_id >", value, "companyLocationCityId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationCityIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("company_location_city_id >=", value, "companyLocationCityId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationCityIdLessThan(Integer value) {
			addCriterion("company_location_city_id <", value, "companyLocationCityId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationCityIdLessThanOrEqualTo(Integer value) {
			addCriterion("company_location_city_id <=", value, "companyLocationCityId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationCityIdIn(List<Integer> values) {
			addCriterion("company_location_city_id in", values, "companyLocationCityId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationCityIdNotIn(List<Integer> values) {
			addCriterion("company_location_city_id not in", values, "companyLocationCityId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationCityIdBetween(Integer value1, Integer value2) {
			addCriterion("company_location_city_id between", value1, value2, "companyLocationCityId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationCityIdNotBetween(Integer value1, Integer value2) {
			addCriterion("company_location_city_id not between", value1, value2, "companyLocationCityId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationTownIdIsNull() {
			addCriterion("company_location_town_id is null");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationTownIdIsNotNull() {
			addCriterion("company_location_town_id is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationTownIdEqualTo(Integer value) {
			addCriterion("company_location_town_id =", value, "companyLocationTownId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationTownIdNotEqualTo(Integer value) {
			addCriterion("company_location_town_id <>", value, "companyLocationTownId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationTownIdGreaterThan(Integer value) {
			addCriterion("company_location_town_id >", value, "companyLocationTownId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationTownIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("company_location_town_id >=", value, "companyLocationTownId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationTownIdLessThan(Integer value) {
			addCriterion("company_location_town_id <", value, "companyLocationTownId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationTownIdLessThanOrEqualTo(Integer value) {
			addCriterion("company_location_town_id <=", value, "companyLocationTownId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationTownIdIn(List<Integer> values) {
			addCriterion("company_location_town_id in", values, "companyLocationTownId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationTownIdNotIn(List<Integer> values) {
			addCriterion("company_location_town_id not in", values, "companyLocationTownId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationTownIdBetween(Integer value1, Integer value2) {
			addCriterion("company_location_town_id between", value1, value2, "companyLocationTownId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationTownIdNotBetween(Integer value1, Integer value2) {
			addCriterion("company_location_town_id not between", value1, value2, "companyLocationTownId");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationIsNull() {
			addCriterion("company_location is null");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationIsNotNull() {
			addCriterion("company_location is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationEqualTo(String value) {
			addCriterion("company_location =", value, "companyLocation");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationNotEqualTo(String value) {
			addCriterion("company_location <>", value, "companyLocation");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationGreaterThan(String value) {
			addCriterion("company_location >", value, "companyLocation");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationGreaterThanOrEqualTo(String value) {
			addCriterion("company_location >=", value, "companyLocation");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationLessThan(String value) {
			addCriterion("company_location <", value, "companyLocation");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationLessThanOrEqualTo(String value) {
			addCriterion("company_location <=", value, "companyLocation");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationLike(String value) {
			addCriterion("company_location like", value, "companyLocation");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationNotLike(String value) {
			addCriterion("company_location not like", value, "companyLocation");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationIn(List<String> values) {
			addCriterion("company_location in", values, "companyLocation");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationNotIn(List<String> values) {
			addCriterion("company_location not in", values, "companyLocation");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationBetween(String value1, String value2) {
			addCriterion("company_location between", value1, value2, "companyLocation");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationNotBetween(String value1, String value2) {
			addCriterion("company_location not between", value1, value2, "companyLocation");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationDetailIsNull() {
			addCriterion("company_location_detail is null");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationDetailIsNotNull() {
			addCriterion("company_location_detail is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationDetailEqualTo(String value) {
			addCriterion("company_location_detail =", value, "companyLocationDetail");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationDetailNotEqualTo(String value) {
			addCriterion("company_location_detail <>", value, "companyLocationDetail");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationDetailGreaterThan(String value) {
			addCriterion("company_location_detail >", value, "companyLocationDetail");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationDetailGreaterThanOrEqualTo(String value) {
			addCriterion("company_location_detail >=", value, "companyLocationDetail");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationDetailLessThan(String value) {
			addCriterion("company_location_detail <", value, "companyLocationDetail");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationDetailLessThanOrEqualTo(String value) {
			addCriterion("company_location_detail <=", value, "companyLocationDetail");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationDetailLike(String value) {
			addCriterion("company_location_detail like", value, "companyLocationDetail");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationDetailNotLike(String value) {
			addCriterion("company_location_detail not like", value, "companyLocationDetail");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationDetailIn(List<String> values) {
			addCriterion("company_location_detail in", values, "companyLocationDetail");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationDetailNotIn(List<String> values) {
			addCriterion("company_location_detail not in", values, "companyLocationDetail");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationDetailBetween(String value1, String value2) {
			addCriterion("company_location_detail between", value1, value2, "companyLocationDetail");
			return (Criteria) this;
		}

		public Criteria andCompanyLocationDetailNotBetween(String value1, String value2) {
			addCriterion("company_location_detail not between", value1, value2, "companyLocationDetail");
			return (Criteria) this;
		}

		public Criteria andContactsNameIsNull() {
			addCriterion("contacts_name is null");
			return (Criteria) this;
		}

		public Criteria andContactsNameIsNotNull() {
			addCriterion("contacts_name is not null");
			return (Criteria) this;
		}

		public Criteria andContactsNameEqualTo(String value) {
			addCriterion("contacts_name =", value, "contactsName");
			return (Criteria) this;
		}

		public Criteria andContactsNameNotEqualTo(String value) {
			addCriterion("contacts_name <>", value, "contactsName");
			return (Criteria) this;
		}

		public Criteria andContactsNameGreaterThan(String value) {
			addCriterion("contacts_name >", value, "contactsName");
			return (Criteria) this;
		}

		public Criteria andContactsNameGreaterThanOrEqualTo(String value) {
			addCriterion("contacts_name >=", value, "contactsName");
			return (Criteria) this;
		}

		public Criteria andContactsNameLessThan(String value) {
			addCriterion("contacts_name <", value, "contactsName");
			return (Criteria) this;
		}

		public Criteria andContactsNameLessThanOrEqualTo(String value) {
			addCriterion("contacts_name <=", value, "contactsName");
			return (Criteria) this;
		}

		public Criteria andContactsNameLike(String value) {
			addCriterion("contacts_name like", value, "contactsName");
			return (Criteria) this;
		}

		public Criteria andContactsNameNotLike(String value) {
			addCriterion("contacts_name not like", value, "contactsName");
			return (Criteria) this;
		}

		public Criteria andContactsNameIn(List<String> values) {
			addCriterion("contacts_name in", values, "contactsName");
			return (Criteria) this;
		}

		public Criteria andContactsNameNotIn(List<String> values) {
			addCriterion("contacts_name not in", values, "contactsName");
			return (Criteria) this;
		}

		public Criteria andContactsNameBetween(String value1, String value2) {
			addCriterion("contacts_name between", value1, value2, "contactsName");
			return (Criteria) this;
		}

		public Criteria andContactsNameNotBetween(String value1, String value2) {
			addCriterion("contacts_name not between", value1, value2, "contactsName");
			return (Criteria) this;
		}

		public Criteria andCompanyEmailIsNull() {
			addCriterion("company_email is null");
			return (Criteria) this;
		}

		public Criteria andCompanyEmailIsNotNull() {
			addCriterion("company_email is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyEmailEqualTo(String value) {
			addCriterion("company_email =", value, "companyEmail");
			return (Criteria) this;
		}

		public Criteria andCompanyEmailNotEqualTo(String value) {
			addCriterion("company_email <>", value, "companyEmail");
			return (Criteria) this;
		}

		public Criteria andCompanyEmailGreaterThan(String value) {
			addCriterion("company_email >", value, "companyEmail");
			return (Criteria) this;
		}

		public Criteria andCompanyEmailGreaterThanOrEqualTo(String value) {
			addCriterion("company_email >=", value, "companyEmail");
			return (Criteria) this;
		}

		public Criteria andCompanyEmailLessThan(String value) {
			addCriterion("company_email <", value, "companyEmail");
			return (Criteria) this;
		}

		public Criteria andCompanyEmailLessThanOrEqualTo(String value) {
			addCriterion("company_email <=", value, "companyEmail");
			return (Criteria) this;
		}

		public Criteria andCompanyEmailLike(String value) {
			addCriterion("company_email like", value, "companyEmail");
			return (Criteria) this;
		}

		public Criteria andCompanyEmailNotLike(String value) {
			addCriterion("company_email not like", value, "companyEmail");
			return (Criteria) this;
		}

		public Criteria andCompanyEmailIn(List<String> values) {
			addCriterion("company_email in", values, "companyEmail");
			return (Criteria) this;
		}

		public Criteria andCompanyEmailNotIn(List<String> values) {
			addCriterion("company_email not in", values, "companyEmail");
			return (Criteria) this;
		}

		public Criteria andCompanyEmailBetween(String value1, String value2) {
			addCriterion("company_email between", value1, value2, "companyEmail");
			return (Criteria) this;
		}

		public Criteria andCompanyEmailNotBetween(String value1, String value2) {
			addCriterion("company_email not between", value1, value2, "companyEmail");
			return (Criteria) this;
		}

		public Criteria andCompanyBankAccountIsNull() {
			addCriterion("company_bank_account is null");
			return (Criteria) this;
		}

		public Criteria andCompanyBankAccountIsNotNull() {
			addCriterion("company_bank_account is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyBankAccountEqualTo(String value) {
			addCriterion("company_bank_account =", value, "companyBankAccount");
			return (Criteria) this;
		}

		public Criteria andCompanyBankAccountNotEqualTo(String value) {
			addCriterion("company_bank_account <>", value, "companyBankAccount");
			return (Criteria) this;
		}

		public Criteria andCompanyBankAccountGreaterThan(String value) {
			addCriterion("company_bank_account >", value, "companyBankAccount");
			return (Criteria) this;
		}

		public Criteria andCompanyBankAccountGreaterThanOrEqualTo(String value) {
			addCriterion("company_bank_account >=", value, "companyBankAccount");
			return (Criteria) this;
		}

		public Criteria andCompanyBankAccountLessThan(String value) {
			addCriterion("company_bank_account <", value, "companyBankAccount");
			return (Criteria) this;
		}

		public Criteria andCompanyBankAccountLessThanOrEqualTo(String value) {
			addCriterion("company_bank_account <=", value, "companyBankAccount");
			return (Criteria) this;
		}

		public Criteria andCompanyBankAccountLike(String value) {
			addCriterion("company_bank_account like", value, "companyBankAccount");
			return (Criteria) this;
		}

		public Criteria andCompanyBankAccountNotLike(String value) {
			addCriterion("company_bank_account not like", value, "companyBankAccount");
			return (Criteria) this;
		}

		public Criteria andCompanyBankAccountIn(List<String> values) {
			addCriterion("company_bank_account in", values, "companyBankAccount");
			return (Criteria) this;
		}

		public Criteria andCompanyBankAccountNotIn(List<String> values) {
			addCriterion("company_bank_account not in", values, "companyBankAccount");
			return (Criteria) this;
		}

		public Criteria andCompanyBankAccountBetween(String value1, String value2) {
			addCriterion("company_bank_account between", value1, value2, "companyBankAccount");
			return (Criteria) this;
		}

		public Criteria andCompanyBankAccountNotBetween(String value1, String value2) {
			addCriterion("company_bank_account not between", value1, value2, "companyBankAccount");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIsNull() {
			addCriterion("phone_number is null");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIsNotNull() {
			addCriterion("phone_number is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberEqualTo(String value) {
			addCriterion("phone_number =", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotEqualTo(String value) {
			addCriterion("phone_number <>", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberGreaterThan(String value) {
			addCriterion("phone_number >", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
			addCriterion("phone_number >=", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLessThan(String value) {
			addCriterion("phone_number <", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
			addCriterion("phone_number <=", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLike(String value) {
			addCriterion("phone_number like", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotLike(String value) {
			addCriterion("phone_number not like", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIn(List<String> values) {
			addCriterion("phone_number in", values, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotIn(List<String> values) {
			addCriterion("phone_number not in", values, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberBetween(String value1, String value2) {
			addCriterion("phone_number between", value1, value2, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotBetween(String value1, String value2) {
			addCriterion("phone_number not between", value1, value2, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andSocialunifiedcreditcodeIsNull() {
			addCriterion("socialUnifiedCreditCode is null");
			return (Criteria) this;
		}

		public Criteria andSocialunifiedcreditcodeIsNotNull() {
			addCriterion("socialUnifiedCreditCode is not null");
			return (Criteria) this;
		}

		public Criteria andSocialunifiedcreditcodeEqualTo(String value) {
			addCriterion("socialUnifiedCreditCode =", value, "socialunifiedcreditcode");
			return (Criteria) this;
		}

		public Criteria andSocialunifiedcreditcodeNotEqualTo(String value) {
			addCriterion("socialUnifiedCreditCode <>", value, "socialunifiedcreditcode");
			return (Criteria) this;
		}

		public Criteria andSocialunifiedcreditcodeGreaterThan(String value) {
			addCriterion("socialUnifiedCreditCode >", value, "socialunifiedcreditcode");
			return (Criteria) this;
		}

		public Criteria andSocialunifiedcreditcodeGreaterThanOrEqualTo(String value) {
			addCriterion("socialUnifiedCreditCode >=", value, "socialunifiedcreditcode");
			return (Criteria) this;
		}

		public Criteria andSocialunifiedcreditcodeLessThan(String value) {
			addCriterion("socialUnifiedCreditCode <", value, "socialunifiedcreditcode");
			return (Criteria) this;
		}

		public Criteria andSocialunifiedcreditcodeLessThanOrEqualTo(String value) {
			addCriterion("socialUnifiedCreditCode <=", value, "socialunifiedcreditcode");
			return (Criteria) this;
		}

		public Criteria andSocialunifiedcreditcodeLike(String value) {
			addCriterion("socialUnifiedCreditCode like", value, "socialunifiedcreditcode");
			return (Criteria) this;
		}

		public Criteria andSocialunifiedcreditcodeNotLike(String value) {
			addCriterion("socialUnifiedCreditCode not like", value, "socialunifiedcreditcode");
			return (Criteria) this;
		}

		public Criteria andSocialunifiedcreditcodeIn(List<String> values) {
			addCriterion("socialUnifiedCreditCode in", values, "socialunifiedcreditcode");
			return (Criteria) this;
		}

		public Criteria andSocialunifiedcreditcodeNotIn(List<String> values) {
			addCriterion("socialUnifiedCreditCode not in", values, "socialunifiedcreditcode");
			return (Criteria) this;
		}

		public Criteria andSocialunifiedcreditcodeBetween(String value1, String value2) {
			addCriterion("socialUnifiedCreditCode between", value1, value2, "socialunifiedcreditcode");
			return (Criteria) this;
		}

		public Criteria andSocialunifiedcreditcodeNotBetween(String value1, String value2) {
			addCriterion("socialUnifiedCreditCode not between", value1, value2, "socialunifiedcreditcode");
			return (Criteria) this;
		}

		public Criteria andImgSrcListIsNull() {
			addCriterion("img_src_list is null");
			return (Criteria) this;
		}

		public Criteria andImgSrcListIsNotNull() {
			addCriterion("img_src_list is not null");
			return (Criteria) this;
		}

		public Criteria andImgSrcListEqualTo(String value) {
			addCriterion("img_src_list =", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListNotEqualTo(String value) {
			addCriterion("img_src_list <>", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListGreaterThan(String value) {
			addCriterion("img_src_list >", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListGreaterThanOrEqualTo(String value) {
			addCriterion("img_src_list >=", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListLessThan(String value) {
			addCriterion("img_src_list <", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListLessThanOrEqualTo(String value) {
			addCriterion("img_src_list <=", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListLike(String value) {
			addCriterion("img_src_list like", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListNotLike(String value) {
			addCriterion("img_src_list not like", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListIn(List<String> values) {
			addCriterion("img_src_list in", values, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListNotIn(List<String> values) {
			addCriterion("img_src_list not in", values, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListBetween(String value1, String value2) {
			addCriterion("img_src_list between", value1, value2, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListNotBetween(String value1, String value2) {
			addCriterion("img_src_list not between", value1, value2, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcIsNull() {
			addCriterion("store_display_img_src is null");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcIsNotNull() {
			addCriterion("store_display_img_src is not null");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcEqualTo(String value) {
			addCriterion("store_display_img_src =", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcNotEqualTo(String value) {
			addCriterion("store_display_img_src <>", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcGreaterThan(String value) {
			addCriterion("store_display_img_src >", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcGreaterThanOrEqualTo(String value) {
			addCriterion("store_display_img_src >=", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcLessThan(String value) {
			addCriterion("store_display_img_src <", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcLessThanOrEqualTo(String value) {
			addCriterion("store_display_img_src <=", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcLike(String value) {
			addCriterion("store_display_img_src like", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcNotLike(String value) {
			addCriterion("store_display_img_src not like", value, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcIn(List<String> values) {
			addCriterion("store_display_img_src in", values, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcNotIn(List<String> values) {
			addCriterion("store_display_img_src not in", values, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcBetween(String value1, String value2) {
			addCriterion("store_display_img_src between", value1, value2, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andStoreDisplayImgSrcNotBetween(String value1, String value2) {
			addCriterion("store_display_img_src not between", value1, value2, "storeDisplayImgSrc");
			return (Criteria) this;
		}

		public Criteria andIsApproveIsNull() {
			addCriterion("is_approve is null");
			return (Criteria) this;
		}

		public Criteria andIsApproveIsNotNull() {
			addCriterion("is_approve is not null");
			return (Criteria) this;
		}

		public Criteria andIsApproveEqualTo(Integer value) {
			addCriterion("is_approve =", value, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveNotEqualTo(Integer value) {
			addCriterion("is_approve <>", value, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveGreaterThan(Integer value) {
			addCriterion("is_approve >", value, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_approve >=", value, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveLessThan(Integer value) {
			addCriterion("is_approve <", value, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveLessThanOrEqualTo(Integer value) {
			addCriterion("is_approve <=", value, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveIn(List<Integer> values) {
			addCriterion("is_approve in", values, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveNotIn(List<Integer> values) {
			addCriterion("is_approve not in", values, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveBetween(Integer value1, Integer value2) {
			addCriterion("is_approve between", value1, value2, "isApprove");
			return (Criteria) this;
		}

		public Criteria andIsApproveNotBetween(Integer value1, Integer value2) {
			addCriterion("is_approve not between", value1, value2, "isApprove");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table service_provider_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table service_provider_identification_company
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 16 17:54:53 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}