package com.gravity.common.support.mybatis.auto.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ServiceProviderServiceExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public ServiceProviderServiceExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andFirstLevelIsNull() {
			addCriterion("first_level is null");
			return (Criteria) this;
		}

		public Criteria andFirstLevelIsNotNull() {
			addCriterion("first_level is not null");
			return (Criteria) this;
		}

		public Criteria andFirstLevelEqualTo(Integer value) {
			addCriterion("first_level =", value, "firstLevel");
			return (Criteria) this;
		}

		public Criteria andFirstLevelNotEqualTo(Integer value) {
			addCriterion("first_level <>", value, "firstLevel");
			return (Criteria) this;
		}

		public Criteria andFirstLevelGreaterThan(Integer value) {
			addCriterion("first_level >", value, "firstLevel");
			return (Criteria) this;
		}

		public Criteria andFirstLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("first_level >=", value, "firstLevel");
			return (Criteria) this;
		}

		public Criteria andFirstLevelLessThan(Integer value) {
			addCriterion("first_level <", value, "firstLevel");
			return (Criteria) this;
		}

		public Criteria andFirstLevelLessThanOrEqualTo(Integer value) {
			addCriterion("first_level <=", value, "firstLevel");
			return (Criteria) this;
		}

		public Criteria andFirstLevelIn(List<Integer> values) {
			addCriterion("first_level in", values, "firstLevel");
			return (Criteria) this;
		}

		public Criteria andFirstLevelNotIn(List<Integer> values) {
			addCriterion("first_level not in", values, "firstLevel");
			return (Criteria) this;
		}

		public Criteria andFirstLevelBetween(Integer value1, Integer value2) {
			addCriterion("first_level between", value1, value2, "firstLevel");
			return (Criteria) this;
		}

		public Criteria andFirstLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("first_level not between", value1, value2, "firstLevel");
			return (Criteria) this;
		}

		public Criteria andSecondLevelIsNull() {
			addCriterion("second_level is null");
			return (Criteria) this;
		}

		public Criteria andSecondLevelIsNotNull() {
			addCriterion("second_level is not null");
			return (Criteria) this;
		}

		public Criteria andSecondLevelEqualTo(Integer value) {
			addCriterion("second_level =", value, "secondLevel");
			return (Criteria) this;
		}

		public Criteria andSecondLevelNotEqualTo(Integer value) {
			addCriterion("second_level <>", value, "secondLevel");
			return (Criteria) this;
		}

		public Criteria andSecondLevelGreaterThan(Integer value) {
			addCriterion("second_level >", value, "secondLevel");
			return (Criteria) this;
		}

		public Criteria andSecondLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("second_level >=", value, "secondLevel");
			return (Criteria) this;
		}

		public Criteria andSecondLevelLessThan(Integer value) {
			addCriterion("second_level <", value, "secondLevel");
			return (Criteria) this;
		}

		public Criteria andSecondLevelLessThanOrEqualTo(Integer value) {
			addCriterion("second_level <=", value, "secondLevel");
			return (Criteria) this;
		}

		public Criteria andSecondLevelIn(List<Integer> values) {
			addCriterion("second_level in", values, "secondLevel");
			return (Criteria) this;
		}

		public Criteria andSecondLevelNotIn(List<Integer> values) {
			addCriterion("second_level not in", values, "secondLevel");
			return (Criteria) this;
		}

		public Criteria andSecondLevelBetween(Integer value1, Integer value2) {
			addCriterion("second_level between", value1, value2, "secondLevel");
			return (Criteria) this;
		}

		public Criteria andSecondLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("second_level not between", value1, value2, "secondLevel");
			return (Criteria) this;
		}

		public Criteria andProvinceIdIsNull() {
			addCriterion("province_id is null");
			return (Criteria) this;
		}

		public Criteria andProvinceIdIsNotNull() {
			addCriterion("province_id is not null");
			return (Criteria) this;
		}

		public Criteria andProvinceIdEqualTo(Integer value) {
			addCriterion("province_id =", value, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdNotEqualTo(Integer value) {
			addCriterion("province_id <>", value, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdGreaterThan(Integer value) {
			addCriterion("province_id >", value, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("province_id >=", value, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdLessThan(Integer value) {
			addCriterion("province_id <", value, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdLessThanOrEqualTo(Integer value) {
			addCriterion("province_id <=", value, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdIn(List<Integer> values) {
			addCriterion("province_id in", values, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdNotIn(List<Integer> values) {
			addCriterion("province_id not in", values, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdBetween(Integer value1, Integer value2) {
			addCriterion("province_id between", value1, value2, "provinceId");
			return (Criteria) this;
		}

		public Criteria andProvinceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("province_id not between", value1, value2, "provinceId");
			return (Criteria) this;
		}

		public Criteria andCityIdIsNull() {
			addCriterion("city_id is null");
			return (Criteria) this;
		}

		public Criteria andCityIdIsNotNull() {
			addCriterion("city_id is not null");
			return (Criteria) this;
		}

		public Criteria andCityIdEqualTo(Integer value) {
			addCriterion("city_id =", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotEqualTo(Integer value) {
			addCriterion("city_id <>", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdGreaterThan(Integer value) {
			addCriterion("city_id >", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("city_id >=", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdLessThan(Integer value) {
			addCriterion("city_id <", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdLessThanOrEqualTo(Integer value) {
			addCriterion("city_id <=", value, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdIn(List<Integer> values) {
			addCriterion("city_id in", values, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotIn(List<Integer> values) {
			addCriterion("city_id not in", values, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdBetween(Integer value1, Integer value2) {
			addCriterion("city_id between", value1, value2, "cityId");
			return (Criteria) this;
		}

		public Criteria andCityIdNotBetween(Integer value1, Integer value2) {
			addCriterion("city_id not between", value1, value2, "cityId");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNull() {
			addCriterion("keyword is null");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNotNull() {
			addCriterion("keyword is not null");
			return (Criteria) this;
		}

		public Criteria andKeywordEqualTo(String value) {
			addCriterion("keyword =", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotEqualTo(String value) {
			addCriterion("keyword <>", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThan(String value) {
			addCriterion("keyword >", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThanOrEqualTo(String value) {
			addCriterion("keyword >=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThan(String value) {
			addCriterion("keyword <", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThanOrEqualTo(String value) {
			addCriterion("keyword <=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLike(String value) {
			addCriterion("keyword like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotLike(String value) {
			addCriterion("keyword not like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordIn(List<String> values) {
			addCriterion("keyword in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotIn(List<String> values) {
			addCriterion("keyword not in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordBetween(String value1, String value2) {
			addCriterion("keyword between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotBetween(String value1, String value2) {
			addCriterion("keyword not between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andOneIntroductionIsNull() {
			addCriterion("one_introduction is null");
			return (Criteria) this;
		}

		public Criteria andOneIntroductionIsNotNull() {
			addCriterion("one_introduction is not null");
			return (Criteria) this;
		}

		public Criteria andOneIntroductionEqualTo(String value) {
			addCriterion("one_introduction =", value, "oneIntroduction");
			return (Criteria) this;
		}

		public Criteria andOneIntroductionNotEqualTo(String value) {
			addCriterion("one_introduction <>", value, "oneIntroduction");
			return (Criteria) this;
		}

		public Criteria andOneIntroductionGreaterThan(String value) {
			addCriterion("one_introduction >", value, "oneIntroduction");
			return (Criteria) this;
		}

		public Criteria andOneIntroductionGreaterThanOrEqualTo(String value) {
			addCriterion("one_introduction >=", value, "oneIntroduction");
			return (Criteria) this;
		}

		public Criteria andOneIntroductionLessThan(String value) {
			addCriterion("one_introduction <", value, "oneIntroduction");
			return (Criteria) this;
		}

		public Criteria andOneIntroductionLessThanOrEqualTo(String value) {
			addCriterion("one_introduction <=", value, "oneIntroduction");
			return (Criteria) this;
		}

		public Criteria andOneIntroductionLike(String value) {
			addCriterion("one_introduction like", value, "oneIntroduction");
			return (Criteria) this;
		}

		public Criteria andOneIntroductionNotLike(String value) {
			addCriterion("one_introduction not like", value, "oneIntroduction");
			return (Criteria) this;
		}

		public Criteria andOneIntroductionIn(List<String> values) {
			addCriterion("one_introduction in", values, "oneIntroduction");
			return (Criteria) this;
		}

		public Criteria andOneIntroductionNotIn(List<String> values) {
			addCriterion("one_introduction not in", values, "oneIntroduction");
			return (Criteria) this;
		}

		public Criteria andOneIntroductionBetween(String value1, String value2) {
			addCriterion("one_introduction between", value1, value2, "oneIntroduction");
			return (Criteria) this;
		}

		public Criteria andOneIntroductionNotBetween(String value1, String value2) {
			addCriterion("one_introduction not between", value1, value2, "oneIntroduction");
			return (Criteria) this;
		}

		public Criteria andOriginalPriceIsNull() {
			addCriterion("original_price is null");
			return (Criteria) this;
		}

		public Criteria andOriginalPriceIsNotNull() {
			addCriterion("original_price is not null");
			return (Criteria) this;
		}

		public Criteria andOriginalPriceEqualTo(Integer value) {
			addCriterion("original_price =", value, "originalPrice");
			return (Criteria) this;
		}

		public Criteria andOriginalPriceNotEqualTo(Integer value) {
			addCriterion("original_price <>", value, "originalPrice");
			return (Criteria) this;
		}

		public Criteria andOriginalPriceGreaterThan(Integer value) {
			addCriterion("original_price >", value, "originalPrice");
			return (Criteria) this;
		}

		public Criteria andOriginalPriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("original_price >=", value, "originalPrice");
			return (Criteria) this;
		}

		public Criteria andOriginalPriceLessThan(Integer value) {
			addCriterion("original_price <", value, "originalPrice");
			return (Criteria) this;
		}

		public Criteria andOriginalPriceLessThanOrEqualTo(Integer value) {
			addCriterion("original_price <=", value, "originalPrice");
			return (Criteria) this;
		}

		public Criteria andOriginalPriceIn(List<Integer> values) {
			addCriterion("original_price in", values, "originalPrice");
			return (Criteria) this;
		}

		public Criteria andOriginalPriceNotIn(List<Integer> values) {
			addCriterion("original_price not in", values, "originalPrice");
			return (Criteria) this;
		}

		public Criteria andOriginalPriceBetween(Integer value1, Integer value2) {
			addCriterion("original_price between", value1, value2, "originalPrice");
			return (Criteria) this;
		}

		public Criteria andOriginalPriceNotBetween(Integer value1, Integer value2) {
			addCriterion("original_price not between", value1, value2, "originalPrice");
			return (Criteria) this;
		}

		public Criteria andGroupPriceIsNull() {
			addCriterion("group_price is null");
			return (Criteria) this;
		}

		public Criteria andGroupPriceIsNotNull() {
			addCriterion("group_price is not null");
			return (Criteria) this;
		}

		public Criteria andGroupPriceEqualTo(Integer value) {
			addCriterion("group_price =", value, "groupPrice");
			return (Criteria) this;
		}

		public Criteria andGroupPriceNotEqualTo(Integer value) {
			addCriterion("group_price <>", value, "groupPrice");
			return (Criteria) this;
		}

		public Criteria andGroupPriceGreaterThan(Integer value) {
			addCriterion("group_price >", value, "groupPrice");
			return (Criteria) this;
		}

		public Criteria andGroupPriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("group_price >=", value, "groupPrice");
			return (Criteria) this;
		}

		public Criteria andGroupPriceLessThan(Integer value) {
			addCriterion("group_price <", value, "groupPrice");
			return (Criteria) this;
		}

		public Criteria andGroupPriceLessThanOrEqualTo(Integer value) {
			addCriterion("group_price <=", value, "groupPrice");
			return (Criteria) this;
		}

		public Criteria andGroupPriceIn(List<Integer> values) {
			addCriterion("group_price in", values, "groupPrice");
			return (Criteria) this;
		}

		public Criteria andGroupPriceNotIn(List<Integer> values) {
			addCriterion("group_price not in", values, "groupPrice");
			return (Criteria) this;
		}

		public Criteria andGroupPriceBetween(Integer value1, Integer value2) {
			addCriterion("group_price between", value1, value2, "groupPrice");
			return (Criteria) this;
		}

		public Criteria andGroupPriceNotBetween(Integer value1, Integer value2) {
			addCriterion("group_price not between", value1, value2, "groupPrice");
			return (Criteria) this;
		}

		public Criteria andImgSrcListIsNull() {
			addCriterion("img_src_list is null");
			return (Criteria) this;
		}

		public Criteria andImgSrcListIsNotNull() {
			addCriterion("img_src_list is not null");
			return (Criteria) this;
		}

		public Criteria andImgSrcListEqualTo(String value) {
			addCriterion("img_src_list =", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListNotEqualTo(String value) {
			addCriterion("img_src_list <>", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListGreaterThan(String value) {
			addCriterion("img_src_list >", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListGreaterThanOrEqualTo(String value) {
			addCriterion("img_src_list >=", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListLessThan(String value) {
			addCriterion("img_src_list <", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListLessThanOrEqualTo(String value) {
			addCriterion("img_src_list <=", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListLike(String value) {
			addCriterion("img_src_list like", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListNotLike(String value) {
			addCriterion("img_src_list not like", value, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListIn(List<String> values) {
			addCriterion("img_src_list in", values, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListNotIn(List<String> values) {
			addCriterion("img_src_list not in", values, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListBetween(String value1, String value2) {
			addCriterion("img_src_list between", value1, value2, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andImgSrcListNotBetween(String value1, String value2) {
			addCriterion("img_src_list not between", value1, value2, "imgSrcList");
			return (Criteria) this;
		}

		public Criteria andOnlineIsNull() {
			addCriterion("online is null");
			return (Criteria) this;
		}

		public Criteria andOnlineIsNotNull() {
			addCriterion("online is not null");
			return (Criteria) this;
		}

		public Criteria andOnlineEqualTo(Integer value) {
			addCriterion("online =", value, "online");
			return (Criteria) this;
		}

		public Criteria andOnlineNotEqualTo(Integer value) {
			addCriterion("online <>", value, "online");
			return (Criteria) this;
		}

		public Criteria andOnlineGreaterThan(Integer value) {
			addCriterion("online >", value, "online");
			return (Criteria) this;
		}

		public Criteria andOnlineGreaterThanOrEqualTo(Integer value) {
			addCriterion("online >=", value, "online");
			return (Criteria) this;
		}

		public Criteria andOnlineLessThan(Integer value) {
			addCriterion("online <", value, "online");
			return (Criteria) this;
		}

		public Criteria andOnlineLessThanOrEqualTo(Integer value) {
			addCriterion("online <=", value, "online");
			return (Criteria) this;
		}

		public Criteria andOnlineIn(List<Integer> values) {
			addCriterion("online in", values, "online");
			return (Criteria) this;
		}

		public Criteria andOnlineNotIn(List<Integer> values) {
			addCriterion("online not in", values, "online");
			return (Criteria) this;
		}

		public Criteria andOnlineBetween(Integer value1, Integer value2) {
			addCriterion("online between", value1, value2, "online");
			return (Criteria) this;
		}

		public Criteria andOnlineNotBetween(Integer value1, Integer value2) {
			addCriterion("online not between", value1, value2, "online");
			return (Criteria) this;
		}

		public Criteria andSalesNumberIsNull() {
			addCriterion("sales_number is null");
			return (Criteria) this;
		}

		public Criteria andSalesNumberIsNotNull() {
			addCriterion("sales_number is not null");
			return (Criteria) this;
		}

		public Criteria andSalesNumberEqualTo(Integer value) {
			addCriterion("sales_number =", value, "salesNumber");
			return (Criteria) this;
		}

		public Criteria andSalesNumberNotEqualTo(Integer value) {
			addCriterion("sales_number <>", value, "salesNumber");
			return (Criteria) this;
		}

		public Criteria andSalesNumberGreaterThan(Integer value) {
			addCriterion("sales_number >", value, "salesNumber");
			return (Criteria) this;
		}

		public Criteria andSalesNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("sales_number >=", value, "salesNumber");
			return (Criteria) this;
		}

		public Criteria andSalesNumberLessThan(Integer value) {
			addCriterion("sales_number <", value, "salesNumber");
			return (Criteria) this;
		}

		public Criteria andSalesNumberLessThanOrEqualTo(Integer value) {
			addCriterion("sales_number <=", value, "salesNumber");
			return (Criteria) this;
		}

		public Criteria andSalesNumberIn(List<Integer> values) {
			addCriterion("sales_number in", values, "salesNumber");
			return (Criteria) this;
		}

		public Criteria andSalesNumberNotIn(List<Integer> values) {
			addCriterion("sales_number not in", values, "salesNumber");
			return (Criteria) this;
		}

		public Criteria andSalesNumberBetween(Integer value1, Integer value2) {
			addCriterion("sales_number between", value1, value2, "salesNumber");
			return (Criteria) this;
		}

		public Criteria andSalesNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("sales_number not between", value1, value2, "salesNumber");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table service_provider_service
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table service_provider_service
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 14 17:37:50 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}