package com.gravity.common.support.mybatis.auto.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserPrivilegeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public UserPrivilegeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPrivilegeNumberIsNull() {
			addCriterion("privilege_number is null");
			return (Criteria) this;
		}

		public Criteria andPrivilegeNumberIsNotNull() {
			addCriterion("privilege_number is not null");
			return (Criteria) this;
		}

		public Criteria andPrivilegeNumberEqualTo(String value) {
			addCriterion("privilege_number =", value, "privilegeNumber");
			return (Criteria) this;
		}

		public Criteria andPrivilegeNumberNotEqualTo(String value) {
			addCriterion("privilege_number <>", value, "privilegeNumber");
			return (Criteria) this;
		}

		public Criteria andPrivilegeNumberGreaterThan(String value) {
			addCriterion("privilege_number >", value, "privilegeNumber");
			return (Criteria) this;
		}

		public Criteria andPrivilegeNumberGreaterThanOrEqualTo(String value) {
			addCriterion("privilege_number >=", value, "privilegeNumber");
			return (Criteria) this;
		}

		public Criteria andPrivilegeNumberLessThan(String value) {
			addCriterion("privilege_number <", value, "privilegeNumber");
			return (Criteria) this;
		}

		public Criteria andPrivilegeNumberLessThanOrEqualTo(String value) {
			addCriterion("privilege_number <=", value, "privilegeNumber");
			return (Criteria) this;
		}

		public Criteria andPrivilegeNumberLike(String value) {
			addCriterion("privilege_number like", value, "privilegeNumber");
			return (Criteria) this;
		}

		public Criteria andPrivilegeNumberNotLike(String value) {
			addCriterion("privilege_number not like", value, "privilegeNumber");
			return (Criteria) this;
		}

		public Criteria andPrivilegeNumberIn(List<String> values) {
			addCriterion("privilege_number in", values, "privilegeNumber");
			return (Criteria) this;
		}

		public Criteria andPrivilegeNumberNotIn(List<String> values) {
			addCriterion("privilege_number not in", values, "privilegeNumber");
			return (Criteria) this;
		}

		public Criteria andPrivilegeNumberBetween(String value1, String value2) {
			addCriterion("privilege_number between", value1, value2, "privilegeNumber");
			return (Criteria) this;
		}

		public Criteria andPrivilegeNumberNotBetween(String value1, String value2) {
			addCriterion("privilege_number not between", value1, value2, "privilegeNumber");
			return (Criteria) this;
		}

		public Criteria andPrivilegeSumIsNull() {
			addCriterion("privilege_sum is null");
			return (Criteria) this;
		}

		public Criteria andPrivilegeSumIsNotNull() {
			addCriterion("privilege_sum is not null");
			return (Criteria) this;
		}

		public Criteria andPrivilegeSumEqualTo(Integer value) {
			addCriterion("privilege_sum =", value, "privilegeSum");
			return (Criteria) this;
		}

		public Criteria andPrivilegeSumNotEqualTo(Integer value) {
			addCriterion("privilege_sum <>", value, "privilegeSum");
			return (Criteria) this;
		}

		public Criteria andPrivilegeSumGreaterThan(Integer value) {
			addCriterion("privilege_sum >", value, "privilegeSum");
			return (Criteria) this;
		}

		public Criteria andPrivilegeSumGreaterThanOrEqualTo(Integer value) {
			addCriterion("privilege_sum >=", value, "privilegeSum");
			return (Criteria) this;
		}

		public Criteria andPrivilegeSumLessThan(Integer value) {
			addCriterion("privilege_sum <", value, "privilegeSum");
			return (Criteria) this;
		}

		public Criteria andPrivilegeSumLessThanOrEqualTo(Integer value) {
			addCriterion("privilege_sum <=", value, "privilegeSum");
			return (Criteria) this;
		}

		public Criteria andPrivilegeSumIn(List<Integer> values) {
			addCriterion("privilege_sum in", values, "privilegeSum");
			return (Criteria) this;
		}

		public Criteria andPrivilegeSumNotIn(List<Integer> values) {
			addCriterion("privilege_sum not in", values, "privilegeSum");
			return (Criteria) this;
		}

		public Criteria andPrivilegeSumBetween(Integer value1, Integer value2) {
			addCriterion("privilege_sum between", value1, value2, "privilegeSum");
			return (Criteria) this;
		}

		public Criteria andPrivilegeSumNotBetween(Integer value1, Integer value2) {
			addCriterion("privilege_sum not between", value1, value2, "privilegeSum");
			return (Criteria) this;
		}

		public Criteria andIsUsedIsNull() {
			addCriterion("is_used is null");
			return (Criteria) this;
		}

		public Criteria andIsUsedIsNotNull() {
			addCriterion("is_used is not null");
			return (Criteria) this;
		}

		public Criteria andIsUsedEqualTo(Integer value) {
			addCriterion("is_used =", value, "isUsed");
			return (Criteria) this;
		}

		public Criteria andIsUsedNotEqualTo(Integer value) {
			addCriterion("is_used <>", value, "isUsed");
			return (Criteria) this;
		}

		public Criteria andIsUsedGreaterThan(Integer value) {
			addCriterion("is_used >", value, "isUsed");
			return (Criteria) this;
		}

		public Criteria andIsUsedGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_used >=", value, "isUsed");
			return (Criteria) this;
		}

		public Criteria andIsUsedLessThan(Integer value) {
			addCriterion("is_used <", value, "isUsed");
			return (Criteria) this;
		}

		public Criteria andIsUsedLessThanOrEqualTo(Integer value) {
			addCriterion("is_used <=", value, "isUsed");
			return (Criteria) this;
		}

		public Criteria andIsUsedIn(List<Integer> values) {
			addCriterion("is_used in", values, "isUsed");
			return (Criteria) this;
		}

		public Criteria andIsUsedNotIn(List<Integer> values) {
			addCriterion("is_used not in", values, "isUsed");
			return (Criteria) this;
		}

		public Criteria andIsUsedBetween(Integer value1, Integer value2) {
			addCriterion("is_used between", value1, value2, "isUsed");
			return (Criteria) this;
		}

		public Criteria andIsUsedNotBetween(Integer value1, Integer value2) {
			addCriterion("is_used not between", value1, value2, "isUsed");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_privilege
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 22 15:49:55 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}