package com.gravity.common.support.mybatis.auto.model;

import java.util.Date;

public class UserOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.id_no
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String idNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.employ_user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer employUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.provider_user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer providerUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.service_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer serviceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.is_cancel
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer isCancel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.is_after_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer isAfterSales;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.deal_price
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer dealPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.service_price
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer servicePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.employ_order_phone
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String employOrderPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.order_remark
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String orderRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.order_remark_file
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String orderRemarkFile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.order_status
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer orderStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.token
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.pay_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.comfirm_receive_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Date comfirmReceiveTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order.finish_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Date finishTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.id
	 * @return  the value of user_order.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.id
	 * @param id  the value for user_order.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.id_no
	 * @return  the value of user_order.id_no
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getIdNo() {
		return idNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.id_no
	 * @param idNo  the value for user_order.id_no
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.employ_user_id
	 * @return  the value of user_order.employ_user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getEmployUserId() {
		return employUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.employ_user_id
	 * @param employUserId  the value for user_order.employ_user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setEmployUserId(Integer employUserId) {
		this.employUserId = employUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.provider_user_id
	 * @return  the value of user_order.provider_user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getProviderUserId() {
		return providerUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.provider_user_id
	 * @param providerUserId  the value for user_order.provider_user_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setProviderUserId(Integer providerUserId) {
		this.providerUserId = providerUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.service_id
	 * @return  the value of user_order.service_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getServiceId() {
		return serviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.service_id
	 * @param serviceId  the value for user_order.service_id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.is_cancel
	 * @return  the value of user_order.is_cancel
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getIsCancel() {
		return isCancel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.is_cancel
	 * @param isCancel  the value for user_order.is_cancel
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setIsCancel(Integer isCancel) {
		this.isCancel = isCancel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.is_after_sales
	 * @return  the value of user_order.is_after_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getIsAfterSales() {
		return isAfterSales;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.is_after_sales
	 * @param isAfterSales  the value for user_order.is_after_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setIsAfterSales(Integer isAfterSales) {
		this.isAfterSales = isAfterSales;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.deal_price
	 * @return  the value of user_order.deal_price
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getDealPrice() {
		return dealPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.deal_price
	 * @param dealPrice  the value for user_order.deal_price
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setDealPrice(Integer dealPrice) {
		this.dealPrice = dealPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.service_price
	 * @return  the value of user_order.service_price
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getServicePrice() {
		return servicePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.service_price
	 * @param servicePrice  the value for user_order.service_price
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setServicePrice(Integer servicePrice) {
		this.servicePrice = servicePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.employ_order_phone
	 * @return  the value of user_order.employ_order_phone
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getEmployOrderPhone() {
		return employOrderPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.employ_order_phone
	 * @param employOrderPhone  the value for user_order.employ_order_phone
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setEmployOrderPhone(String employOrderPhone) {
		this.employOrderPhone = employOrderPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.order_remark
	 * @return  the value of user_order.order_remark
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getOrderRemark() {
		return orderRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.order_remark
	 * @param orderRemark  the value for user_order.order_remark
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setOrderRemark(String orderRemark) {
		this.orderRemark = orderRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.order_remark_file
	 * @return  the value of user_order.order_remark_file
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getOrderRemarkFile() {
		return orderRemarkFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.order_remark_file
	 * @param orderRemarkFile  the value for user_order.order_remark_file
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setOrderRemarkFile(String orderRemarkFile) {
		this.orderRemarkFile = orderRemarkFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.order_status
	 * @return  the value of user_order.order_status
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.order_status
	 * @param orderStatus  the value for user_order.order_status
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.token
	 * @return  the value of user_order.token
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.token
	 * @param token  the value for user_order.token
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.create_time
	 * @return  the value of user_order.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.create_time
	 * @param createTime  the value for user_order.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.pay_time
	 * @return  the value of user_order.pay_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.pay_time
	 * @param payTime  the value for user_order.pay_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.comfirm_receive_time
	 * @return  the value of user_order.comfirm_receive_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Date getComfirmReceiveTime() {
		return comfirmReceiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.comfirm_receive_time
	 * @param comfirmReceiveTime  the value for user_order.comfirm_receive_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setComfirmReceiveTime(Date comfirmReceiveTime) {
		this.comfirmReceiveTime = comfirmReceiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order.finish_time
	 * @return  the value of user_order.finish_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Date getFinishTime() {
		return finishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order.finish_time
	 * @param finishTime  the value for user_order.finish_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		UserOrder other = (UserOrder) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getIdNo() == null ? other.getIdNo() == null : this.getIdNo().equals(other.getIdNo()))
				&& (this.getEmployUserId() == null ? other.getEmployUserId() == null : this.getEmployUserId().equals(
						other.getEmployUserId()))
				&& (this.getProviderUserId() == null ? other.getProviderUserId() == null : this.getProviderUserId()
						.equals(other.getProviderUserId()))
				&& (this.getServiceId() == null ? other.getServiceId() == null : this.getServiceId().equals(
						other.getServiceId()))
				&& (this.getIsCancel() == null ? other.getIsCancel() == null : this.getIsCancel().equals(
						other.getIsCancel()))
				&& (this.getIsAfterSales() == null ? other.getIsAfterSales() == null : this.getIsAfterSales().equals(
						other.getIsAfterSales()))
				&& (this.getDealPrice() == null ? other.getDealPrice() == null : this.getDealPrice().equals(
						other.getDealPrice()))
				&& (this.getServicePrice() == null ? other.getServicePrice() == null : this.getServicePrice().equals(
						other.getServicePrice()))
				&& (this.getEmployOrderPhone() == null ? other.getEmployOrderPhone() == null : this
						.getEmployOrderPhone().equals(other.getEmployOrderPhone()))
				&& (this.getOrderRemark() == null ? other.getOrderRemark() == null : this.getOrderRemark().equals(
						other.getOrderRemark()))
				&& (this.getOrderRemarkFile() == null ? other.getOrderRemarkFile() == null : this.getOrderRemarkFile()
						.equals(other.getOrderRemarkFile()))
				&& (this.getOrderStatus() == null ? other.getOrderStatus() == null : this.getOrderStatus().equals(
						other.getOrderStatus()))
				&& (this.getToken() == null ? other.getToken() == null : this.getToken().equals(other.getToken()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(
						other.getCreateTime()))
				&& (this.getPayTime() == null ? other.getPayTime() == null : this.getPayTime().equals(
						other.getPayTime()))
				&& (this.getComfirmReceiveTime() == null ? other.getComfirmReceiveTime() == null : this
						.getComfirmReceiveTime().equals(other.getComfirmReceiveTime()))
				&& (this.getFinishTime() == null ? other.getFinishTime() == null : this.getFinishTime().equals(
						other.getFinishTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getIdNo() == null) ? 0 : getIdNo().hashCode());
		result = prime * result + ((getEmployUserId() == null) ? 0 : getEmployUserId().hashCode());
		result = prime * result + ((getProviderUserId() == null) ? 0 : getProviderUserId().hashCode());
		result = prime * result + ((getServiceId() == null) ? 0 : getServiceId().hashCode());
		result = prime * result + ((getIsCancel() == null) ? 0 : getIsCancel().hashCode());
		result = prime * result + ((getIsAfterSales() == null) ? 0 : getIsAfterSales().hashCode());
		result = prime * result + ((getDealPrice() == null) ? 0 : getDealPrice().hashCode());
		result = prime * result + ((getServicePrice() == null) ? 0 : getServicePrice().hashCode());
		result = prime * result + ((getEmployOrderPhone() == null) ? 0 : getEmployOrderPhone().hashCode());
		result = prime * result + ((getOrderRemark() == null) ? 0 : getOrderRemark().hashCode());
		result = prime * result + ((getOrderRemarkFile() == null) ? 0 : getOrderRemarkFile().hashCode());
		result = prime * result + ((getOrderStatus() == null) ? 0 : getOrderStatus().hashCode());
		result = prime * result + ((getToken() == null) ? 0 : getToken().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getPayTime() == null) ? 0 : getPayTime().hashCode());
		result = prime * result + ((getComfirmReceiveTime() == null) ? 0 : getComfirmReceiveTime().hashCode());
		result = prime * result + ((getFinishTime() == null) ? 0 : getFinishTime().hashCode());
		return result;
	}
}