package com.gravity.common.support.mybatis.auto.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserOrderExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public UserOrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNoIsNull() {
			addCriterion("id_no is null");
			return (Criteria) this;
		}

		public Criteria andIdNoIsNotNull() {
			addCriterion("id_no is not null");
			return (Criteria) this;
		}

		public Criteria andIdNoEqualTo(String value) {
			addCriterion("id_no =", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoNotEqualTo(String value) {
			addCriterion("id_no <>", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoGreaterThan(String value) {
			addCriterion("id_no >", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoGreaterThanOrEqualTo(String value) {
			addCriterion("id_no >=", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoLessThan(String value) {
			addCriterion("id_no <", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoLessThanOrEqualTo(String value) {
			addCriterion("id_no <=", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoLike(String value) {
			addCriterion("id_no like", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoNotLike(String value) {
			addCriterion("id_no not like", value, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoIn(List<String> values) {
			addCriterion("id_no in", values, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoNotIn(List<String> values) {
			addCriterion("id_no not in", values, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoBetween(String value1, String value2) {
			addCriterion("id_no between", value1, value2, "idNo");
			return (Criteria) this;
		}

		public Criteria andIdNoNotBetween(String value1, String value2) {
			addCriterion("id_no not between", value1, value2, "idNo");
			return (Criteria) this;
		}

		public Criteria andEmployUserIdIsNull() {
			addCriterion("employ_user_id is null");
			return (Criteria) this;
		}

		public Criteria andEmployUserIdIsNotNull() {
			addCriterion("employ_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmployUserIdEqualTo(Integer value) {
			addCriterion("employ_user_id =", value, "employUserId");
			return (Criteria) this;
		}

		public Criteria andEmployUserIdNotEqualTo(Integer value) {
			addCriterion("employ_user_id <>", value, "employUserId");
			return (Criteria) this;
		}

		public Criteria andEmployUserIdGreaterThan(Integer value) {
			addCriterion("employ_user_id >", value, "employUserId");
			return (Criteria) this;
		}

		public Criteria andEmployUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("employ_user_id >=", value, "employUserId");
			return (Criteria) this;
		}

		public Criteria andEmployUserIdLessThan(Integer value) {
			addCriterion("employ_user_id <", value, "employUserId");
			return (Criteria) this;
		}

		public Criteria andEmployUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("employ_user_id <=", value, "employUserId");
			return (Criteria) this;
		}

		public Criteria andEmployUserIdIn(List<Integer> values) {
			addCriterion("employ_user_id in", values, "employUserId");
			return (Criteria) this;
		}

		public Criteria andEmployUserIdNotIn(List<Integer> values) {
			addCriterion("employ_user_id not in", values, "employUserId");
			return (Criteria) this;
		}

		public Criteria andEmployUserIdBetween(Integer value1, Integer value2) {
			addCriterion("employ_user_id between", value1, value2, "employUserId");
			return (Criteria) this;
		}

		public Criteria andEmployUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("employ_user_id not between", value1, value2, "employUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdIsNull() {
			addCriterion("provider_user_id is null");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdIsNotNull() {
			addCriterion("provider_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdEqualTo(Integer value) {
			addCriterion("provider_user_id =", value, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdNotEqualTo(Integer value) {
			addCriterion("provider_user_id <>", value, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdGreaterThan(Integer value) {
			addCriterion("provider_user_id >", value, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("provider_user_id >=", value, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdLessThan(Integer value) {
			addCriterion("provider_user_id <", value, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("provider_user_id <=", value, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdIn(List<Integer> values) {
			addCriterion("provider_user_id in", values, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdNotIn(List<Integer> values) {
			addCriterion("provider_user_id not in", values, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdBetween(Integer value1, Integer value2) {
			addCriterion("provider_user_id between", value1, value2, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andProviderUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("provider_user_id not between", value1, value2, "providerUserId");
			return (Criteria) this;
		}

		public Criteria andServiceIdIsNull() {
			addCriterion("service_id is null");
			return (Criteria) this;
		}

		public Criteria andServiceIdIsNotNull() {
			addCriterion("service_id is not null");
			return (Criteria) this;
		}

		public Criteria andServiceIdEqualTo(Integer value) {
			addCriterion("service_id =", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdNotEqualTo(Integer value) {
			addCriterion("service_id <>", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdGreaterThan(Integer value) {
			addCriterion("service_id >", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("service_id >=", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdLessThan(Integer value) {
			addCriterion("service_id <", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdLessThanOrEqualTo(Integer value) {
			addCriterion("service_id <=", value, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdIn(List<Integer> values) {
			addCriterion("service_id in", values, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdNotIn(List<Integer> values) {
			addCriterion("service_id not in", values, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdBetween(Integer value1, Integer value2) {
			addCriterion("service_id between", value1, value2, "serviceId");
			return (Criteria) this;
		}

		public Criteria andServiceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("service_id not between", value1, value2, "serviceId");
			return (Criteria) this;
		}

		public Criteria andIsCancelIsNull() {
			addCriterion("is_cancel is null");
			return (Criteria) this;
		}

		public Criteria andIsCancelIsNotNull() {
			addCriterion("is_cancel is not null");
			return (Criteria) this;
		}

		public Criteria andIsCancelEqualTo(Integer value) {
			addCriterion("is_cancel =", value, "isCancel");
			return (Criteria) this;
		}

		public Criteria andIsCancelNotEqualTo(Integer value) {
			addCriterion("is_cancel <>", value, "isCancel");
			return (Criteria) this;
		}

		public Criteria andIsCancelGreaterThan(Integer value) {
			addCriterion("is_cancel >", value, "isCancel");
			return (Criteria) this;
		}

		public Criteria andIsCancelGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_cancel >=", value, "isCancel");
			return (Criteria) this;
		}

		public Criteria andIsCancelLessThan(Integer value) {
			addCriterion("is_cancel <", value, "isCancel");
			return (Criteria) this;
		}

		public Criteria andIsCancelLessThanOrEqualTo(Integer value) {
			addCriterion("is_cancel <=", value, "isCancel");
			return (Criteria) this;
		}

		public Criteria andIsCancelIn(List<Integer> values) {
			addCriterion("is_cancel in", values, "isCancel");
			return (Criteria) this;
		}

		public Criteria andIsCancelNotIn(List<Integer> values) {
			addCriterion("is_cancel not in", values, "isCancel");
			return (Criteria) this;
		}

		public Criteria andIsCancelBetween(Integer value1, Integer value2) {
			addCriterion("is_cancel between", value1, value2, "isCancel");
			return (Criteria) this;
		}

		public Criteria andIsCancelNotBetween(Integer value1, Integer value2) {
			addCriterion("is_cancel not between", value1, value2, "isCancel");
			return (Criteria) this;
		}

		public Criteria andIsAfterSalesIsNull() {
			addCriterion("is_after_sales is null");
			return (Criteria) this;
		}

		public Criteria andIsAfterSalesIsNotNull() {
			addCriterion("is_after_sales is not null");
			return (Criteria) this;
		}

		public Criteria andIsAfterSalesEqualTo(Integer value) {
			addCriterion("is_after_sales =", value, "isAfterSales");
			return (Criteria) this;
		}

		public Criteria andIsAfterSalesNotEqualTo(Integer value) {
			addCriterion("is_after_sales <>", value, "isAfterSales");
			return (Criteria) this;
		}

		public Criteria andIsAfterSalesGreaterThan(Integer value) {
			addCriterion("is_after_sales >", value, "isAfterSales");
			return (Criteria) this;
		}

		public Criteria andIsAfterSalesGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_after_sales >=", value, "isAfterSales");
			return (Criteria) this;
		}

		public Criteria andIsAfterSalesLessThan(Integer value) {
			addCriterion("is_after_sales <", value, "isAfterSales");
			return (Criteria) this;
		}

		public Criteria andIsAfterSalesLessThanOrEqualTo(Integer value) {
			addCriterion("is_after_sales <=", value, "isAfterSales");
			return (Criteria) this;
		}

		public Criteria andIsAfterSalesIn(List<Integer> values) {
			addCriterion("is_after_sales in", values, "isAfterSales");
			return (Criteria) this;
		}

		public Criteria andIsAfterSalesNotIn(List<Integer> values) {
			addCriterion("is_after_sales not in", values, "isAfterSales");
			return (Criteria) this;
		}

		public Criteria andIsAfterSalesBetween(Integer value1, Integer value2) {
			addCriterion("is_after_sales between", value1, value2, "isAfterSales");
			return (Criteria) this;
		}

		public Criteria andIsAfterSalesNotBetween(Integer value1, Integer value2) {
			addCriterion("is_after_sales not between", value1, value2, "isAfterSales");
			return (Criteria) this;
		}

		public Criteria andDealPriceIsNull() {
			addCriterion("deal_price is null");
			return (Criteria) this;
		}

		public Criteria andDealPriceIsNotNull() {
			addCriterion("deal_price is not null");
			return (Criteria) this;
		}

		public Criteria andDealPriceEqualTo(Integer value) {
			addCriterion("deal_price =", value, "dealPrice");
			return (Criteria) this;
		}

		public Criteria andDealPriceNotEqualTo(Integer value) {
			addCriterion("deal_price <>", value, "dealPrice");
			return (Criteria) this;
		}

		public Criteria andDealPriceGreaterThan(Integer value) {
			addCriterion("deal_price >", value, "dealPrice");
			return (Criteria) this;
		}

		public Criteria andDealPriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("deal_price >=", value, "dealPrice");
			return (Criteria) this;
		}

		public Criteria andDealPriceLessThan(Integer value) {
			addCriterion("deal_price <", value, "dealPrice");
			return (Criteria) this;
		}

		public Criteria andDealPriceLessThanOrEqualTo(Integer value) {
			addCriterion("deal_price <=", value, "dealPrice");
			return (Criteria) this;
		}

		public Criteria andDealPriceIn(List<Integer> values) {
			addCriterion("deal_price in", values, "dealPrice");
			return (Criteria) this;
		}

		public Criteria andDealPriceNotIn(List<Integer> values) {
			addCriterion("deal_price not in", values, "dealPrice");
			return (Criteria) this;
		}

		public Criteria andDealPriceBetween(Integer value1, Integer value2) {
			addCriterion("deal_price between", value1, value2, "dealPrice");
			return (Criteria) this;
		}

		public Criteria andDealPriceNotBetween(Integer value1, Integer value2) {
			addCriterion("deal_price not between", value1, value2, "dealPrice");
			return (Criteria) this;
		}

		public Criteria andServicePriceIsNull() {
			addCriterion("service_price is null");
			return (Criteria) this;
		}

		public Criteria andServicePriceIsNotNull() {
			addCriterion("service_price is not null");
			return (Criteria) this;
		}

		public Criteria andServicePriceEqualTo(Integer value) {
			addCriterion("service_price =", value, "servicePrice");
			return (Criteria) this;
		}

		public Criteria andServicePriceNotEqualTo(Integer value) {
			addCriterion("service_price <>", value, "servicePrice");
			return (Criteria) this;
		}

		public Criteria andServicePriceGreaterThan(Integer value) {
			addCriterion("service_price >", value, "servicePrice");
			return (Criteria) this;
		}

		public Criteria andServicePriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("service_price >=", value, "servicePrice");
			return (Criteria) this;
		}

		public Criteria andServicePriceLessThan(Integer value) {
			addCriterion("service_price <", value, "servicePrice");
			return (Criteria) this;
		}

		public Criteria andServicePriceLessThanOrEqualTo(Integer value) {
			addCriterion("service_price <=", value, "servicePrice");
			return (Criteria) this;
		}

		public Criteria andServicePriceIn(List<Integer> values) {
			addCriterion("service_price in", values, "servicePrice");
			return (Criteria) this;
		}

		public Criteria andServicePriceNotIn(List<Integer> values) {
			addCriterion("service_price not in", values, "servicePrice");
			return (Criteria) this;
		}

		public Criteria andServicePriceBetween(Integer value1, Integer value2) {
			addCriterion("service_price between", value1, value2, "servicePrice");
			return (Criteria) this;
		}

		public Criteria andServicePriceNotBetween(Integer value1, Integer value2) {
			addCriterion("service_price not between", value1, value2, "servicePrice");
			return (Criteria) this;
		}

		public Criteria andEmployOrderPhoneIsNull() {
			addCriterion("employ_order_phone is null");
			return (Criteria) this;
		}

		public Criteria andEmployOrderPhoneIsNotNull() {
			addCriterion("employ_order_phone is not null");
			return (Criteria) this;
		}

		public Criteria andEmployOrderPhoneEqualTo(String value) {
			addCriterion("employ_order_phone =", value, "employOrderPhone");
			return (Criteria) this;
		}

		public Criteria andEmployOrderPhoneNotEqualTo(String value) {
			addCriterion("employ_order_phone <>", value, "employOrderPhone");
			return (Criteria) this;
		}

		public Criteria andEmployOrderPhoneGreaterThan(String value) {
			addCriterion("employ_order_phone >", value, "employOrderPhone");
			return (Criteria) this;
		}

		public Criteria andEmployOrderPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("employ_order_phone >=", value, "employOrderPhone");
			return (Criteria) this;
		}

		public Criteria andEmployOrderPhoneLessThan(String value) {
			addCriterion("employ_order_phone <", value, "employOrderPhone");
			return (Criteria) this;
		}

		public Criteria andEmployOrderPhoneLessThanOrEqualTo(String value) {
			addCriterion("employ_order_phone <=", value, "employOrderPhone");
			return (Criteria) this;
		}

		public Criteria andEmployOrderPhoneLike(String value) {
			addCriterion("employ_order_phone like", value, "employOrderPhone");
			return (Criteria) this;
		}

		public Criteria andEmployOrderPhoneNotLike(String value) {
			addCriterion("employ_order_phone not like", value, "employOrderPhone");
			return (Criteria) this;
		}

		public Criteria andEmployOrderPhoneIn(List<String> values) {
			addCriterion("employ_order_phone in", values, "employOrderPhone");
			return (Criteria) this;
		}

		public Criteria andEmployOrderPhoneNotIn(List<String> values) {
			addCriterion("employ_order_phone not in", values, "employOrderPhone");
			return (Criteria) this;
		}

		public Criteria andEmployOrderPhoneBetween(String value1, String value2) {
			addCriterion("employ_order_phone between", value1, value2, "employOrderPhone");
			return (Criteria) this;
		}

		public Criteria andEmployOrderPhoneNotBetween(String value1, String value2) {
			addCriterion("employ_order_phone not between", value1, value2, "employOrderPhone");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkIsNull() {
			addCriterion("order_remark is null");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkIsNotNull() {
			addCriterion("order_remark is not null");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkEqualTo(String value) {
			addCriterion("order_remark =", value, "orderRemark");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkNotEqualTo(String value) {
			addCriterion("order_remark <>", value, "orderRemark");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkGreaterThan(String value) {
			addCriterion("order_remark >", value, "orderRemark");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("order_remark >=", value, "orderRemark");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkLessThan(String value) {
			addCriterion("order_remark <", value, "orderRemark");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkLessThanOrEqualTo(String value) {
			addCriterion("order_remark <=", value, "orderRemark");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkLike(String value) {
			addCriterion("order_remark like", value, "orderRemark");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkNotLike(String value) {
			addCriterion("order_remark not like", value, "orderRemark");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkIn(List<String> values) {
			addCriterion("order_remark in", values, "orderRemark");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkNotIn(List<String> values) {
			addCriterion("order_remark not in", values, "orderRemark");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkBetween(String value1, String value2) {
			addCriterion("order_remark between", value1, value2, "orderRemark");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkNotBetween(String value1, String value2) {
			addCriterion("order_remark not between", value1, value2, "orderRemark");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkFileIsNull() {
			addCriterion("order_remark_file is null");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkFileIsNotNull() {
			addCriterion("order_remark_file is not null");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkFileEqualTo(String value) {
			addCriterion("order_remark_file =", value, "orderRemarkFile");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkFileNotEqualTo(String value) {
			addCriterion("order_remark_file <>", value, "orderRemarkFile");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkFileGreaterThan(String value) {
			addCriterion("order_remark_file >", value, "orderRemarkFile");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkFileGreaterThanOrEqualTo(String value) {
			addCriterion("order_remark_file >=", value, "orderRemarkFile");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkFileLessThan(String value) {
			addCriterion("order_remark_file <", value, "orderRemarkFile");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkFileLessThanOrEqualTo(String value) {
			addCriterion("order_remark_file <=", value, "orderRemarkFile");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkFileLike(String value) {
			addCriterion("order_remark_file like", value, "orderRemarkFile");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkFileNotLike(String value) {
			addCriterion("order_remark_file not like", value, "orderRemarkFile");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkFileIn(List<String> values) {
			addCriterion("order_remark_file in", values, "orderRemarkFile");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkFileNotIn(List<String> values) {
			addCriterion("order_remark_file not in", values, "orderRemarkFile");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkFileBetween(String value1, String value2) {
			addCriterion("order_remark_file between", value1, value2, "orderRemarkFile");
			return (Criteria) this;
		}

		public Criteria andOrderRemarkFileNotBetween(String value1, String value2) {
			addCriterion("order_remark_file not between", value1, value2, "orderRemarkFile");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNull() {
			addCriterion("order_status is null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNotNull() {
			addCriterion("order_status is not null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusEqualTo(Integer value) {
			addCriterion("order_status =", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotEqualTo(Integer value) {
			addCriterion("order_status <>", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThan(Integer value) {
			addCriterion("order_status >", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_status >=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThan(Integer value) {
			addCriterion("order_status <", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
			addCriterion("order_status <=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIn(List<Integer> values) {
			addCriterion("order_status in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotIn(List<Integer> values) {
			addCriterion("order_status not in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
			addCriterion("order_status between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("order_status not between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andTokenIsNull() {
			addCriterion("token is null");
			return (Criteria) this;
		}

		public Criteria andTokenIsNotNull() {
			addCriterion("token is not null");
			return (Criteria) this;
		}

		public Criteria andTokenEqualTo(String value) {
			addCriterion("token =", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotEqualTo(String value) {
			addCriterion("token <>", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenGreaterThan(String value) {
			addCriterion("token >", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenGreaterThanOrEqualTo(String value) {
			addCriterion("token >=", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenLessThan(String value) {
			addCriterion("token <", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenLessThanOrEqualTo(String value) {
			addCriterion("token <=", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenLike(String value) {
			addCriterion("token like", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotLike(String value) {
			addCriterion("token not like", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenIn(List<String> values) {
			addCriterion("token in", values, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotIn(List<String> values) {
			addCriterion("token not in", values, "token");
			return (Criteria) this;
		}

		public Criteria andTokenBetween(String value1, String value2) {
			addCriterion("token between", value1, value2, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotBetween(String value1, String value2) {
			addCriterion("token not between", value1, value2, "token");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNull() {
			addCriterion("pay_time is null");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNotNull() {
			addCriterion("pay_time is not null");
			return (Criteria) this;
		}

		public Criteria andPayTimeEqualTo(Date value) {
			addCriterion("pay_time =", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotEqualTo(Date value) {
			addCriterion("pay_time <>", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThan(Date value) {
			addCriterion("pay_time >", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("pay_time >=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThan(Date value) {
			addCriterion("pay_time <", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThanOrEqualTo(Date value) {
			addCriterion("pay_time <=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeIn(List<Date> values) {
			addCriterion("pay_time in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotIn(List<Date> values) {
			addCriterion("pay_time not in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeBetween(Date value1, Date value2) {
			addCriterion("pay_time between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotBetween(Date value1, Date value2) {
			addCriterion("pay_time not between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andComfirmReceiveTimeIsNull() {
			addCriterion("comfirm_receive_time is null");
			return (Criteria) this;
		}

		public Criteria andComfirmReceiveTimeIsNotNull() {
			addCriterion("comfirm_receive_time is not null");
			return (Criteria) this;
		}

		public Criteria andComfirmReceiveTimeEqualTo(Date value) {
			addCriterion("comfirm_receive_time =", value, "comfirmReceiveTime");
			return (Criteria) this;
		}

		public Criteria andComfirmReceiveTimeNotEqualTo(Date value) {
			addCriterion("comfirm_receive_time <>", value, "comfirmReceiveTime");
			return (Criteria) this;
		}

		public Criteria andComfirmReceiveTimeGreaterThan(Date value) {
			addCriterion("comfirm_receive_time >", value, "comfirmReceiveTime");
			return (Criteria) this;
		}

		public Criteria andComfirmReceiveTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("comfirm_receive_time >=", value, "comfirmReceiveTime");
			return (Criteria) this;
		}

		public Criteria andComfirmReceiveTimeLessThan(Date value) {
			addCriterion("comfirm_receive_time <", value, "comfirmReceiveTime");
			return (Criteria) this;
		}

		public Criteria andComfirmReceiveTimeLessThanOrEqualTo(Date value) {
			addCriterion("comfirm_receive_time <=", value, "comfirmReceiveTime");
			return (Criteria) this;
		}

		public Criteria andComfirmReceiveTimeIn(List<Date> values) {
			addCriterion("comfirm_receive_time in", values, "comfirmReceiveTime");
			return (Criteria) this;
		}

		public Criteria andComfirmReceiveTimeNotIn(List<Date> values) {
			addCriterion("comfirm_receive_time not in", values, "comfirmReceiveTime");
			return (Criteria) this;
		}

		public Criteria andComfirmReceiveTimeBetween(Date value1, Date value2) {
			addCriterion("comfirm_receive_time between", value1, value2, "comfirmReceiveTime");
			return (Criteria) this;
		}

		public Criteria andComfirmReceiveTimeNotBetween(Date value1, Date value2) {
			addCriterion("comfirm_receive_time not between", value1, value2, "comfirmReceiveTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeIsNull() {
			addCriterion("finish_time is null");
			return (Criteria) this;
		}

		public Criteria andFinishTimeIsNotNull() {
			addCriterion("finish_time is not null");
			return (Criteria) this;
		}

		public Criteria andFinishTimeEqualTo(Date value) {
			addCriterion("finish_time =", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeNotEqualTo(Date value) {
			addCriterion("finish_time <>", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeGreaterThan(Date value) {
			addCriterion("finish_time >", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("finish_time >=", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeLessThan(Date value) {
			addCriterion("finish_time <", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeLessThanOrEqualTo(Date value) {
			addCriterion("finish_time <=", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeIn(List<Date> values) {
			addCriterion("finish_time in", values, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeNotIn(List<Date> values) {
			addCriterion("finish_time not in", values, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeBetween(Date value1, Date value2) {
			addCriterion("finish_time between", value1, value2, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeNotBetween(Date value1, Date value2) {
			addCriterion("finish_time not between", value1, value2, "finishTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_order
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_order
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 22 14:49:37 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}