package com.gravity.common.support.mybatis.auto.model;

import java.util.Date;

public class UserPrivilege {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_privilege.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_privilege.privilege_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private String privilegeNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_privilege.privilege_sum
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer privilegeSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_privilege.is_used
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Integer isUsed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_privilege.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_privilege.id
	 * @return  the value of user_privilege.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_privilege.id
	 * @param id  the value for user_privilege.id
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_privilege.privilege_number
	 * @return  the value of user_privilege.privilege_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public String getPrivilegeNumber() {
		return privilegeNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_privilege.privilege_number
	 * @param privilegeNumber  the value for user_privilege.privilege_number
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setPrivilegeNumber(String privilegeNumber) {
		this.privilegeNumber = privilegeNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_privilege.privilege_sum
	 * @return  the value of user_privilege.privilege_sum
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getPrivilegeSum() {
		return privilegeSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_privilege.privilege_sum
	 * @param privilegeSum  the value for user_privilege.privilege_sum
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setPrivilegeSum(Integer privilegeSum) {
		this.privilegeSum = privilegeSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_privilege.is_used
	 * @return  the value of user_privilege.is_used
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Integer getIsUsed() {
		return isUsed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_privilege.is_used
	 * @param isUsed  the value for user_privilege.is_used
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setIsUsed(Integer isUsed) {
		this.isUsed = isUsed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_privilege.create_time
	 * @return  the value of user_privilege.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_privilege.create_time
	 * @param createTime  the value for user_privilege.create_time
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		UserPrivilege other = (UserPrivilege) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getPrivilegeNumber() == null ? other.getPrivilegeNumber() == null : this.getPrivilegeNumber()
						.equals(other.getPrivilegeNumber()))
				&& (this.getPrivilegeSum() == null ? other.getPrivilegeSum() == null : this.getPrivilegeSum().equals(
						other.getPrivilegeSum()))
				&& (this.getIsUsed() == null ? other.getIsUsed() == null : this.getIsUsed().equals(other.getIsUsed()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(
						other.getCreateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getPrivilegeNumber() == null) ? 0 : getPrivilegeNumber().hashCode());
		result = prime * result + ((getPrivilegeSum() == null) ? 0 : getPrivilegeSum().hashCode());
		result = prime * result + ((getIsUsed() == null) ? 0 : getIsUsed().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		return result;
	}
}