package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.AdminBasicInfo;
import com.gravity.common.support.mybatis.auto.model.AdminBasicInfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@Mapper
public interface AdminBasicInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_basic_info
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(AdminBasicInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_basic_info
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(AdminBasicInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_basic_info
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_basic_info
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(AdminBasicInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_basic_info
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(AdminBasicInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_basic_info
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<AdminBasicInfo> selectByExample(AdminBasicInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_basic_info
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	AdminBasicInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_basic_info
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") AdminBasicInfo record, @Param("example") AdminBasicInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_basic_info
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") AdminBasicInfo record, @Param("example") AdminBasicInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_basic_info
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(AdminBasicInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin_basic_info
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(AdminBasicInfo record);
}