package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.CategorySecond;
import com.gravity.common.support.mybatis.auto.model.CategorySecondExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CategorySecondMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_second
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(CategorySecondExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_second
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(CategorySecondExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_second
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_second
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(CategorySecond record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_second
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(CategorySecond record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_second
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<CategorySecond> selectByExample(CategorySecondExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_second
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	CategorySecond selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_second
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") CategorySecond record, @Param("example") CategorySecondExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_second
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") CategorySecond record, @Param("example") CategorySecondExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_second
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(CategorySecond record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_second
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(CategorySecond record);
}