package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.CategoryMapping;
import com.gravity.common.support.mybatis.auto.model.CategoryMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CategoryMappingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_mapping
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(CategoryMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_mapping
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(CategoryMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_mapping
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_mapping
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(CategoryMapping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_mapping
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(CategoryMapping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_mapping
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<CategoryMapping> selectByExample(CategoryMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_mapping
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	CategoryMapping selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_mapping
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") CategoryMapping record,
			@Param("example") CategoryMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_mapping
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") CategoryMapping record, @Param("example") CategoryMappingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_mapping
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(CategoryMapping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_mapping
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(CategoryMapping record);
}