package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.CategoryFirst;
import com.gravity.common.support.mybatis.auto.model.CategoryFirstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CategoryFirstMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_first
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(CategoryFirstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_first
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(CategoryFirstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_first
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_first
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(CategoryFirst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_first
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(CategoryFirst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_first
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<CategoryFirst> selectByExample(CategoryFirstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_first
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	CategoryFirst selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_first
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") CategoryFirst record, @Param("example") CategoryFirstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_first
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") CategoryFirst record, @Param("example") CategoryFirstExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_first
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(CategoryFirst record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_first
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(CategoryFirst record);

	List<CategoryFirst> selectAll();
}