package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.EmployIdentificationCompany;
import com.gravity.common.support.mybatis.auto.model.EmployIdentificationCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EmployIdentificationCompanyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(EmployIdentificationCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(EmployIdentificationCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(EmployIdentificationCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(EmployIdentificationCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<EmployIdentificationCompany> selectByExample(EmployIdentificationCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	EmployIdentificationCompany selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") EmployIdentificationCompany record,
			@Param("example") EmployIdentificationCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") EmployIdentificationCompany record,
			@Param("example") EmployIdentificationCompanyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(EmployIdentificationCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_company
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(EmployIdentificationCompany record);
}