package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.EmployIdentificationPerson;
import com.gravity.common.support.mybatis.auto.model.EmployIdentificationPersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EmployIdentificationPersonMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(EmployIdentificationPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(EmployIdentificationPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(EmployIdentificationPerson record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(EmployIdentificationPerson record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<EmployIdentificationPerson> selectByExample(EmployIdentificationPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	EmployIdentificationPerson selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") EmployIdentificationPerson record,
			@Param("example") EmployIdentificationPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") EmployIdentificationPerson record,
			@Param("example") EmployIdentificationPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(EmployIdentificationPerson record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employ_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(EmployIdentificationPerson record);
}