package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.api.common.view.model.ServiceEvaluateDetailModel;
import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.Evaluate;
import com.gravity.common.support.mybatis.auto.model.EvaluateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EvaluateMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(EvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(EvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(Evaluate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(Evaluate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<Evaluate> selectByExample(EvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	Evaluate selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Evaluate record, @Param("example") EvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") Evaluate record, @Param("example") EvaluateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(Evaluate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table evaluate
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(Evaluate record);

	List<ServiceEvaluateDetailModel> selectByServiceId(@Param("serviceId") int serviceId, @Param("begin") int begin, @Param("onePageSize") int onePageSize);
    
    int selectCountByServiceId(@Param("serviceId") int serviceId);
}