package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.HomeCompanyLogo;
import com.gravity.common.support.mybatis.auto.model.HomeCompanyLogoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface HomeCompanyLogoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table home_company_logo
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(HomeCompanyLogoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table home_company_logo
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(HomeCompanyLogoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table home_company_logo
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table home_company_logo
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(HomeCompanyLogo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table home_company_logo
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(HomeCompanyLogo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table home_company_logo
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<HomeCompanyLogo> selectByExample(HomeCompanyLogoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table home_company_logo
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	HomeCompanyLogo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table home_company_logo
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HomeCompanyLogo record,
			@Param("example") HomeCompanyLogoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table home_company_logo
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") HomeCompanyLogo record, @Param("example") HomeCompanyLogoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table home_company_logo
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(HomeCompanyLogo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table home_company_logo
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(HomeCompanyLogo record);
}