package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.PayToPlatform;
import com.gravity.common.support.mybatis.auto.model.PayToPlatformExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@Mapper
public interface PayToPlatformMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_to_platform
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(PayToPlatformExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_to_platform
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(PayToPlatformExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_to_platform
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_to_platform
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(PayToPlatform record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_to_platform
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(PayToPlatform record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_to_platform
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<PayToPlatform> selectByExample(PayToPlatformExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_to_platform
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	PayToPlatform selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_to_platform
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") PayToPlatform record, @Param("example") PayToPlatformExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_to_platform
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") PayToPlatform record, @Param("example") PayToPlatformExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_to_platform
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(PayToPlatform record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_to_platform
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(PayToPlatform record);
}