package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.ProviderAccount;
import com.gravity.common.support.mybatis.auto.model.ProviderAccountExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProviderAccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_account
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(ProviderAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_account
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(ProviderAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_account
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_account
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(ProviderAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_account
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(ProviderAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_account
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<ProviderAccount> selectByExample(ProviderAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_account
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	ProviderAccount selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_account
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ProviderAccount record,
			@Param("example") ProviderAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_account
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") ProviderAccount record, @Param("example") ProviderAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_account
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(ProviderAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_account
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(ProviderAccount record);
}