package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.ProviderWithDraw;
import com.gravity.common.support.mybatis.auto.model.ProviderWithDrawExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProviderWithDrawMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_with_draw
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(ProviderWithDrawExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_with_draw
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(ProviderWithDrawExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_with_draw
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_with_draw
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(ProviderWithDraw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_with_draw
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(ProviderWithDraw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_with_draw
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<ProviderWithDraw> selectByExample(ProviderWithDrawExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_with_draw
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	ProviderWithDraw selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_with_draw
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ProviderWithDraw record,
			@Param("example") ProviderWithDrawExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_with_draw
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") ProviderWithDraw record, @Param("example") ProviderWithDrawExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_with_draw
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(ProviderWithDraw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_with_draw
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(ProviderWithDraw record);

	List<ProviderWithDraw> selectByPage(@Param(value = "page") int page, @Param(value = "onePageSize") int onePageSize);
	
	List<ProviderWithDraw> selectByStatusAndPage(@Param(value = "status") int status, @Param(value = "page") int page, @Param(value = "onePageSize") int onePageSize);
	
	int allCount();
	
	int allCountByUserId(@Param(value = "userId") int userId);
	
	int allCountByStatus(@Param(value = "status") int status);
}