package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.api.common.view.model.ProviderMyAccountIncomeDBModel;
import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.ProviderIncome;
import com.gravity.common.support.mybatis.auto.model.ProviderIncomeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProviderIncomeMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_income
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(ProviderIncomeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_income
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(ProviderIncomeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_income
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_income
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(ProviderIncome record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_income
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(ProviderIncome record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_income
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<ProviderIncome> selectByExample(ProviderIncomeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_income
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	ProviderIncome selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_income
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ProviderIncome record, @Param("example") ProviderIncomeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_income
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") ProviderIncome record, @Param("example") ProviderIncomeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_income
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(ProviderIncome record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table provider_income
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(ProviderIncome record);

	List<ProviderMyAccountIncomeDBModel> selectByPageAndProviderId(@Param(value="providerId") int providerId, @Param(value="beginSize") int beginSize, @Param(value="onePageSize") int onePageSize);
    
    int selectCountByProviderId(@Param(value="providerId") int providerId);
}