package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.api.common.view.model.ServiceLocationModel;
import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.ServiceProviderIdentificationPerson;
import com.gravity.common.support.mybatis.auto.model.ServiceProviderIdentificationPersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ServiceProviderIdentificationPersonMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(ServiceProviderIdentificationPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(ServiceProviderIdentificationPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(ServiceProviderIdentificationPerson record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(ServiceProviderIdentificationPerson record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<ServiceProviderIdentificationPerson> selectByExample(ServiceProviderIdentificationPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	ServiceProviderIdentificationPerson selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ServiceProviderIdentificationPerson record,
			@Param("example") ServiceProviderIdentificationPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") ServiceProviderIdentificationPerson record,
			@Param("example") ServiceProviderIdentificationPersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(ServiceProviderIdentificationPerson record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_provider_identification_person
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(ServiceProviderIdentificationPerson record);

	List<ServiceLocationModel> selectAllServiceLocation ();
}