package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.ServiceSales;
import com.gravity.common.support.mybatis.auto.model.ServiceSalesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ServiceSalesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(ServiceSalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(ServiceSalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(ServiceSales record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(ServiceSales record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<ServiceSales> selectByExample(ServiceSalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	ServiceSales selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ServiceSales record, @Param("example") ServiceSalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") ServiceSales record, @Param("example") ServiceSalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(ServiceSales record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_sales
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(ServiceSales record);
}