package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.ServiceProviderService;
import com.gravity.common.support.mybatis.auto.model.Users;
import com.gravity.common.support.mybatis.auto.model.UsersExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@Mapper
public interface UsersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<Users> selectByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	Users selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Users record, @Param("example") UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(Users record);

	int userCountByGroupType(@Param(value="groupType") int groupType);
	
	int userCountByGroupTypeAndPhone(@Param(value="phone") String phone, @Param(value="groupType") int groupType);
	
	int userCountByGroupTypeAndTypeCp(@Param(value="typeCp") int typeCp, @Param(value="groupType") int groupType);
	
	List<Users> selectUsersByPageAndGroupType(@Param(value="groupType") int groupType, @Param(value="page") int page, @Param(value="onePageSize") int onePageSize);
	
	List<Users> selectUsersByPageAndGroupTypeAndPhone(@Param(value="phone") String phone, @Param(value="groupType") int groupType, @Param(value="page") int page, @Param(value="onePageSize") int onePageSize);
	
	List<Users> selectUsersByPageAndGroupTypeAndTypeCp(@Param(value="typeCp") int typeCp, @Param(value="groupType") int groupType, @Param(value="page") int page, @Param(value="onePageSize") int onePageSize);
}