package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.UserPrivilege;
import com.gravity.common.support.mybatis.auto.model.UserPrivilegeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserPrivilegeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(UserPrivilegeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(UserPrivilegeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(UserPrivilege record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(UserPrivilege record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<UserPrivilege> selectByExample(UserPrivilegeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	UserPrivilege selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") UserPrivilege record, @Param("example") UserPrivilegeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") UserPrivilege record, @Param("example") UserPrivilegeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(UserPrivilege record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_privilege
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(UserPrivilege record);
}