package com.gravity.common.support.mybatis.auto.repository;

import com.gravity.common.support.mybatis.Mapper;
import com.gravity.common.support.mybatis.auto.model.UsersVerifyCode;
import com.gravity.common.support.mybatis.auto.model.UsersVerifyCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UsersVerifyCodeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_verify_code
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int countByExample(UsersVerifyCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_verify_code
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByExample(UsersVerifyCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_verify_code
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_verify_code
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insert(UsersVerifyCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_verify_code
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int insertSelective(UsersVerifyCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_verify_code
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	List<UsersVerifyCode> selectByExample(UsersVerifyCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_verify_code
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	UsersVerifyCode selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_verify_code
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") UsersVerifyCode record,
			@Param("example") UsersVerifyCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_verify_code
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByExample(@Param("record") UsersVerifyCode record, @Param("example") UsersVerifyCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_verify_code
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKeySelective(UsersVerifyCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users_verify_code
	 * @mbggenerated  Sat Sep 24 10:43:53 CST 2016
	 */
	int updateByPrimaryKey(UsersVerifyCode record);
}